maven-resolver-api/src/main/java/org/eclipse/aether/transform/FileTransformer.java, maven-resolver-api/src/main/java/org/eclipse/aether/transform/TransformException.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultInstallerTest.java, pom.xml
=> [MRESOLVER-63] FileTransformer#transformData(File) should also throw TransformException

maven-resolver-synccontext-redisson/pom.xml, maven-resolver-synccontext-redisson/src/main/java/org/eclipse/aether/internal/impl/TrackingFileManager.java, maven-resolver-synccontext-redisson/src/main/java/org/eclipse/aether/synccontext/RedissonSyncContextFactory.java, maven-resolver-synccontext-redisson/src/site/markdown/index.md.vm, maven-resolver-synccontext-redisson/src/site/site.xml, pom.xml
=> [MRESOLVER-131] Introduce a Redisson-based SyncContextFactory

maven-resolver-api/pom.xml, maven-resolver-connector-basic/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-synccontext-global/pom.xml, maven-resolver-synccontext-redisson/pom.xml, maven-resolver-test-util/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, maven-resolver-util/pom.xml, pom.xml
Jenkins is failing because Java 8 is enforced. Now, we need Java 8 at
release time only.
=> Move OSGi metadata generation to apache-release profile

maven-resolver-impl/src/main/java/org/eclipse/aether/impl/DefaultServiceLocator.java
Deprecate service locator implementation as well, as integrators
usually extend this class (see Maven for example), and they don't
deal with deprecated interfaces directly, so the fact they are deprecated
may be missed at first sight.
By deprecating this implementation as well, the integrators
will get a warning in their build and/or IDEs, so intent will be
more obvious.
=> [MRESOLVER-160] Deprecate service locator

maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/guice/DemoResolverModule.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/ChecksumExtractor.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporterFactory.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/Nexus2ChecksumExtractor.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/XChecksumChecksumExtractor.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/ChecksumUtils.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/ChecksumUtilTest.java, src/site/markdown/configuration.md, src/site/markdown/included-checksum-strategies.md, src/site/site.xml
Refactor and make it pluggable. Also, make it work with Maven Central.
This change broadens "smart checksum" support in Resolver, and
gets them from HTTP response header, if present. So far only
Nexus2 was supported, but this now adds more implementations,
so for example Central is supported now as well, hence, to
download a JAR from Central will now take only 1 HTTP request
and not 2, that effectively **halves count of HTTP requests done
today against central** as well.
This change improves transport-http only, Wagon transport is
a big burden of layers of layers of abstraction of abstraction above
and am unsure how to do this there.
High level changes:
* introduce `ChecksumExtractor` component and provide OOTB 3 implementations for it (the nexus2 was inlined, this is like "factor out …
=> [MRESOLVER-231] Extend smart checksum support

maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java, maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java, maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumValidator.java, maven-resolver-connector-basic/src/test/java/org/eclipse/aether/connector/basic/ChecksumValidatorTest.java, maven-resolver-connector-basic/src/test/java/org/eclipse/aether/connector/basic/TestChecksumAlgorithmSelector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/AbstractChecksumPolicy.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/DefaultChecksumAlgorithmFactorySelector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultArtifactResolverTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/FailChecksumPolicyTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactoryTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/WarnChecksumPolicyTest.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumAlgorithmFactorySelector.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumPolicy.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ProvidedChecksumsSource.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/layout/RepositoryLayout.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/transport/GetTask.java
This feature allows Resolver to get "provided" checksums ahead
of remote transport (resolution), hence, it may operate with
"good known" checksums for example (or use any other source).
High level changes:
* introduce ProvidedChecksumsSource component
* modify basic connector and checksum validator to support provided checksums
* implement file based checksums source
---
https://issues.apache.org/jira/browse/MRESOLVER-234
=> [MRESOLVER-234] Provided checksums

maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, maven-resolver-demos/maven-resolver-demo-snippets/pom.xml, maven-resolver-demos/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, pom.xml
Maven Resolver demos both used Maven but declared different versions, lift to parent module maven version. Also, update the dependencies where applicable.
Changes:
* update demos Maven version in demos to 3.8.4
* update resolver impl Commons Lang to 3.12.0 (was 3.8.1)
* update resolver named locks Hazelcast to 5.0.1 (was 4.1.2)
* update transport http httpCore to 4.4.15 (was 4.4.14)
* update transport wagon Wagon to 3.5.1 (was 3.4.3)
* update slf4j (globally) to 1.7.36 (was 1.7.32)
---
https://issues.apache.org/jira/browse/MRESOLVER-239
=> [MRESOLVER-239] Update dependencies

maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-hazelcast/src/main/java/org/eclipse/aether/named/hazelcast/DirectHazelcastSemaphoreProvider.java, maven-resolver-named-locks-hazelcast/src/main/java/org/eclipse/aether/named/hazelcast/HazelcastCPSemaphoreNamedLockFactory.java, maven-resolver-named-locks-hazelcast/src/main/java/org/eclipse/aether/named/hazelcast/HazelcastClientCPSemaphoreNamedLockFactory.java, maven-resolver-named-locks-hazelcast/src/main/java/org/eclipse/aether/named/hazelcast/HazelcastSemaphoreNamedLockFactory.java, maven-resolver-named-locks-hazelcast/src/main/java/org/eclipse/aether/named/hazelcast/HazelcastSemaphoreProvider.java, maven-resolver-named-locks-hazelcast/src/site/markdown/index.md.vm, maven-resolver-named-locks-hazelcast/src/site/site.xml, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/HazelcastCPSemaphoreNamedLockFactoryIT.java, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/HazelcastClientCPSemaphoreAdapterIT.java, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/HazelcastClientCPSemaphoreNamedLockFactoryIT.java, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/HazelcastClientUtils.java, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/NamedLockFactoryAdapterTestSupport.java, maven-resolver-named-locks-hazelcast/src/test/java/org/eclipse/aether/named/hazelcast/NamedLockFactoryTestSupport.java, maven-resolver-named-locks-hazelcast/src/test/resources/hazelcast-client.xml, maven-resolver-named-locks-hazelcast/src/test/resources/hazelcast.xml
Main intent is to properly isolate ITs, but did other cleanup as well
like patch update of Hazelcast and documentation updated as well.
High level changes:
* POM update with new patch release of HZ
* removed obsolete `destroySemaphore` parameter (always false), factored out semaphore provision
* updated all 4 ITs to form random named clusters (hence to prevent outer HZ instance joining)
* provided hazelcast and hazelcast-client XML fixed (used wrong schema)
* Tests reformatted to maven codestyle (changes best viewed with `?w=1`)
---
https://issues.apache.org/jira/browse/MRESOLVER-245
=> [MRESOLVER-245] Isolate and update tests

maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-hazelcast/src/site/markdown/index.md.vm, maven-resolver-named-locks-hazelcast/src/test/resources/hazelcast-client.xml, maven-resolver-named-locks-hazelcast/src/test/resources/hazelcast.xml
Update Hazelcast from 5.0.2 to latest 5.1.1. This is really
not a game changer, as Hazelcast 5.x is API compatible, so
end users may choose which version to use for real at runtime.
---
https://issues.apache.org/jira/browse/MRESOLVER-249
=> [MRESOLVER-249] Update Hazelcast to 5.1.1

src/site/xdoc/index.xml
Instead to refer to version that "works with" (and forget about 3.9.x),
better state Java level, and mention how to run on Java 7 bound
maven 3.8.x. Do not mention any later maven version, and we are not
fortune tellers (as 3.9.x can show).
=> Reword warning on site

maven-resolver-impl/src/main/java/org/eclipse/aether/impl/DefaultServiceLocator.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/ArtifactPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalPathPrefixComposerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactorySupport.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerFactory.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultLocalPathPrefixComposerFactoryTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/EnhancedSplitLocalRepositoryManagerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/FileProvidedChecksumsSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerTest.java, src/site/markdown/configuration.md, src/site/markdown/local-repository.md, src/site/site.xml
LocalRepositoryManager path composition was enclosed
into SimpleLocalRepositoryManager in not-quite reusable
manner. Make it reusable, by making it into a component.
Currently FileProvidedChecksumsSource was reusing local
paths, is adjusted now.
Also, make LRM implementations more encapsulated and
clear up many ctors leaving only one for simplicity.
---
[MRESOLVER-252](https://issues.apache.org/jira/browse/MRESOLVER-252)
=> [MRESOLVER-252] Make LRM path composition reusable

maven-resolver-transport-http/pom.xml
Jetty is used in tests for Transport HTTP only.
=> [MRESOLVER-255] Update Jetty to 9.4.46.v20220331

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalPathPrefixComposerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactorySupport.java
This PR is just here as a reminder for upcoming
1.8.1 and also cleans up "TBD" versions.
To be merged just before release AFTER ensured all
`@since TBD`s are covered.
=> Prepare 1.8.1 release

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactoryTest.java
There is a discrepancy when a checksum is attached (so not added
by resolver itself), and resolver will checksum it if the algorithm
is not configured (ie. default config used but SHA512 added).
This makes it work as expected, as checksum recognition works
now against ALL SUPPORTED and not configured ONLY checksums).
---
https://issues.apache.org/jira/browse/MRESOLVER-265
=> [MRESOLVER-265] Checksum of checksum

maven-resolver-named-locks/src/site/markdown/index.md.vm, src/site/markdown/local-repository.md
Rework local repo page available from TLP, move "uninteresting" simple LRM to bottom, add intro about locking, to not have it buried in some module...
Inspired by https://github.com/apache/maven-resolver/pull/184
=> Add some TLP doco about shared local repo access

maven-resolver-util/src/test/java/org/eclipse/aether/util/version/GenericVersionSchemeTest.java
bound works
compare with MNG-7106
=> add test to ensure that a version constraint having same upper and lower

maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, pom.xml
Upgrade following plugins:
* m-invoker-p
* m-install-p
* m-deploy-p
Require Maven 3.8.4+ for building.
=> [MRESOLVER-280] Upgrade invoker, install, deploy, require Mvn 3.8.4+

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceSupport.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/ArtifactResolverPostProcessorSupport.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessor.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceTestSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSourceTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/DirectoryUtils.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
High level changes:
* support class should meddle way less, it is here to provide some utils and protect from future API changes
* sparse source: use `FileProcessor` for both, checksum read and write (instead to mix in `Files.write`)
* summary source: heavily enhanced, on save it truncate or merges with existing summary file, added change detection (prevents save when no change to save), summary file is written out atomically, and finally file format is made GNU Coreutils formatted, hence is usable with GNU sha1sum and alike OS tools
* TrustedChecksumsArtifactResolverPostProcessor got new config "snapshots" to validate/record snapshots as well (by default, they should be "in-house", hence trusted).
* introduce FileUtils, Java NIO2 based file writing utility
For both checksum sources the …
=> [MRESOLVER-279] Simplify and improve trusted checksum sources

maven-resolver-impl/src/main/java/org/eclipse/aether/impl/DefaultServiceLocator.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/RemoteRepositoryFilterManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/DefaultRemoteRepositoryFilterManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/FilteringRepositoryConnector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultArtifactResolverTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultMetadataResolverTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/Filters.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceTestSupport.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/filter/RemoteRepositoryFilter.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/filter/RemoteRepositoryFilterSource.java, src/site/markdown/remote-repository-filtering.md, src/site/site.xml
RemoteRepository filter feature and some filter implementations:
* groupId filter: is able to fiter artifacts from remote repository by groupId (manually authored or "recorded").
* prefix filter: uses prefixes file published by remote repositories (or manually authored).
Like any new feature, they are by default disabled/dormant, and need to be explicitly enabled.
About feature: the "remote repository filter" feature is able to filter (allow or disallow) artifact to be resolved (so even if locally present) from given remote repository. This is "all or nothing" filter, so it neglects usage context of artifact. In other words, if you filter out "maven-plugin-api", you probably rendered your build broken (same for any plugin dependencies). Simply put, if you have some "unwanted" artifact …
=> [MRESOLVER-274] Remote Repository Filter

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/DependencyProcessingContext.java
This PR is for parallel POM downloading, the idea is a bit different than https://github.com/ibabiankou/maven-resolver/pull/2/files:
- only parallelize the VersionRange and ArtifactDesciptor resolution part (poms.xml & maven-metadata.xml downloading in parallel) as the poms downloading or maven-metadata.xml is the most slow part.
- Pure dependency resolution logic and the [skip logic](https://github.com/apache/maven-resolver/pull/158) are still run in sequence.
=> [MRESOLVER-7] download poms in parallel

maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositorySystemSession.java
Maven ITs running against https://github.com/apache/maven/pull/831 fails. Reason is "too late" registration of onClose handler to session, when it is already readOnoy.
There are valid cases in Maven when interaction with resolver (that would "lazily" init SyncContext) happens way late, when session is already made readOnly.
Fix: adding onCloseHandler should NOT be affected by readOnly state of session, as it merely means it's members like LRM, etc are "fixed", but session data etc are all still mutable.
Similarly, due lazy init, some components may -- as in above valid cases -- register some handler when session is already read only.
This change makes all Maven ITs pass with this resolver.
=> [MRESOLVER-278] Session close and onClose hooks fix

maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/AllResolverDemos.java, maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/resolver/Resolver.java, maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/resolver/ResolverDemo.java
The module `maven-resolver-demo-snippets` already had UT named `AllResolverDemos` that simply ran all the demos 3 times (sisu, guice and SL).
There was one last snippet that was not "tied in", so this PR ties that in as well.
=> Make ResolverDemo run as part of AllResolverDemos too.

maven-resolver-api/src/main/java/org/eclipse/aether/AbstractForwardingRepositorySystemSession.java, maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositorySystemSession.java, maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystem.java, maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystemSession.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/DefaultServiceLocator.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/RepositorySystemLifecycle.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystemLifecycle.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessor.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/DefaultSyncContextFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactorySelector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/ParameterizedNamedLockFactorySelector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceTestSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollectorTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/checksums/TrustedChecksumsSource.java, src/site/markdown/configuration.md
Drops problematic onSessionClose, keeps only onSystemClose support. Issue will be adjusted accordingly.
Key changes:
* undone all related to onSessionClose
* kept onRepositorySystemClose + shutdown
* all 3 users on onSessionClose (locking + 2 "recording" features) will act on shutdown
* moved out of session.data use as it is completely unreliable, now singleton components hold caches (hence the shutdown persistence)
* DefaultSyncContext: fixed as explained, does not use system properties anymore, but is made pretty much same as before https://github.com/apache/maven-resolver/pull/196
* renamed all new components to `camelCase`
----
https://issues.apache.org/jira/browse/MRESOLVER-278
=> [MRESOLVER-278] On repository system shutdown

maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java
Basic connector was last that handled closed state in a bit "wonky" way, rework to use it AtomicBoolean as everything else in resolver.
---
https://issues.apache.org/jira/browse/MRESOLVER-286
=> [MRESOLVER-286] Improve basic connector closed state handling

maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/providers/FileLockNamedLockFactory.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/FileLockNamedLock.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/Retry.java, maven-resolver-named-locks/src/test/java/org/eclipse/aether/named/RetryTest.java
That has concurrency issue at FS level when it comes to deletion of files.
This PR adds several "tweak" flags that allow users on Windows to circumvent the issue.
By default (w/o any user "tweaking") the file locking should now work fine on Windows, not leaving behind any "garbage" (0 byte lock files).
Related Java bug: https://bugs.openjdk.org/browse/JDK-8252883
---
https://issues.apache.org/jira/browse/MRESOLVER-285
=> [MRESOLVER-285] File locking tweaks for Windows OS

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector.java
As discussed in https://issues.apache.org/jira/browse/MNG-5896, the param in code does not match with the one in doc:
https://maven.apache.org/resolver/configuration.html
DOC: aether.dependencyCollector.impl
Code: aether.collector.impl
---
https://issues.apache.org/jira/browse/MRESOLVER-292
=> [MRESOLVER-292] Fix configuration name in documentation to match with actual name

maven-resolver-connector-basic/pom.xml, maven-resolver-demos/maven-resolver-demo-snippets/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-named-locks-redisson/src/site/markdown/index.md.vm, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, pom.xml
Update dependencies, mostly to align with Maven.
Updates:
* Guice to 5.1.0 (align with Maven 3.9,0)
* Hazelcast 5.1.1 -> 5.1.4 (bugfixes)
* Redisson 3.17.5 -> 3.17.7 (bugfixes)
* plexus-utils multiple -> 3.5.0 (runtime dependency)
* http transport used HttpClient commons-codec 1.11 -> 1.15 (to get rid of CVEs)
* wagon transport Wagon API 3.5.1 -> 3.5.2
* test dependency Jetty 9.4.46 -> 9.4.49 (to get rid of CVEs, but not affecting us, as this is test dependency)
* test dependency Mockito core 3.7.7 -> 4.8.1
Make sure plexus-utils, guava are NEVER in compile scope, as resolver should not use classes from these
(exception is Wagon Transport).
---
https://issues.apache.org/jira/browse/MRESOLVER-293
=> [MRESOLVER-293] Update dependencies

maven-resolver-api/src/main/java/org/eclipse/aether/collection/CollectStepData.java, maven-resolver-connector-basic/src/test/java/org/eclipse/aether/connector/basic/TestChecksumAlgorithmSelector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/DefaultChecksumAlgorithmFactorySelector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumAlgorithmFactorySelector.java, pom.xml, src/site/markdown/api-compatibility.md, src/site/site.xml
Fix japicmp configuration and explain what we "promise" to clients and what we "expect" from them.
---
https://issues.apache.org/jira/browse/MRESOLVER-294
=> [MRESOLVER-294] Fix JapiCmp configuration and document it

maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java, maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumCalculator.java, maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumValidator.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/TrackingFileManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSource.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumAlgorithmHelper.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/transport/GetTask.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/transport/PutTask.java, maven-resolver-transport-file/src/main/java/org/eclipse/aether/transport/file/FileTransporter.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
Drop old and legacy code doing smart(er) things, use common shared primitives instead.
Also, make IO handling stricter, do not be "forgiving" by swallowing IOEx-es as they will inevitably lead to failures, it does not make resolver more robust, but actually makes it harder to figure out the problems, and could lead to incomplete downloads or uploads. Simply put, if reading or writing a file on disk fails with IOEx, do not assume "is fine" in any case. This probably shows some existing issue like permissions or whatever.
---
https://issues.apache.org/jira/browse/MRESOLVER-290
=> [MRESOLVER-290] Expand use of atomic file ops

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultFileProcessor.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultFileProcessorTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
The `FileProcessor.write( File, InputStream )` method  is completely broken, it always fails. This method is used ONLY when FileTransformer is present. Result of plain oversight and not being covered by tests.
---
https://issues.apache.org/jira/browse/MRESOLVER-296
=> [MRESOLVER-269] FileProcessor.write( File, InputStream ) is defunct

maven-resolver-connector-basic/src/test/java/org/eclipse/aether/connector/basic/TestChecksumAlgorithmSelector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/DefaultChecksumAlgorithmFactorySelector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumAlgorithmFactory.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/connector/checksum/ChecksumAlgorithmFactorySelector.java
Expose it on selector., and also start "bending" things toward Artifact instead of plain string matching.
---
https://issues.apache.org/jira/browse/MRESOLVER-303
=> [MRESOLVER-303] Make checksum detection reusable

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java
As blocked is really about block remote access. Locally cached things should not be affected, but current solution did not cover all execution paths.
---
https://issues.apache.org/jira/browse/MRESOLVER-305
=> [MRESOLVER-305] Handle blocked state at connector level

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java
In case remote repository defines unsupported layout, filter should just let it pass (as resolver will gracefully fail with it anyway), while throwing RuntimeException caused abruptly stopped build.
---
https://issues.apache.org/jira/browse/MRESOLVER-309
=> [MRESOLVER-309] Do not kill the build when unkown remote layout

maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/ChecksumValidator.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
Collocated temp file should NOT use Files.createTempFile as it uses 0600 perms and not relies implicitly on umask. For "randomized" name using very same technique as Files.createTempFile does under the hood.
Remove one unjustified use of collocated temp file.
---
https://issues.apache.org/jira/browse/MRESOLVER-313
=> [MRESOLVER-313] Wrong FS permissions on cached artifacts.

maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NameMappers.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapterFactoryImpl.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/DiscriminatingNameMapperProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/FileGAVNameMapperProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/FileHashingGAVNameMapperProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/GAVNameMapperProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/StaticNameMapperProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/package-info.java
javax.inject is and should be optional (used only when Guice and/or Sisu is being used), but in case SL is being used no javax.inject should be needed.
This rule was violated in 1.9.0 commit 5566bd5b3b0e59d124d820e6274da8e2da7804b0 where `javax.inject.Provider` was used in conjuction with SL as well.
This fix introduces `NameMappers` helper static class that constructs name mappers, and javax.inject.Provider classes are used ONLY when in Guice/Sisu, are NOT used with conjunction of SL.
---
https://issues.apache.org/jira/browse/MRESOLVER-298
=> [MRESOLVER-298] Make javax.inject optional again

maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java, src/site/markdown/configuration.md
Make basic connector be able to perform parallel PUTs in very same manner as it did so far parallel GETs.
Still, there is a "safety switch" to turn off this new feature that is ENABLED by default.
Effects:
* set threads to 1: GET and PUT are executed sequentially
* set parallelPut to false: Behave as Maven 3.8.x line was
* default: perform parallel GETs and PUTs
---
https://issues.apache.org/jira/browse/MRESOLVER-319
=> [MRESOLVER-319] Parallel Deploy Support

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/NearestVersionSelector.java
When resolving artifact from issue, the DF collector enters endless loop. But the loop is NOT in collecting, it happens when DF detect unsolvable problem, and tries to report it. To report it, it needs to visit the graph of collected nodes, but that graph contains loops (and it is expected).
But, the problem is that PathRecordingDependencyVisitor used to collect paths chokes on loops.
Fix: just like in RepositorySystem#resolveDependencies, wrap up the graph visitor into TreeDependencyVisitor, that creates tree-like (loopless, tree by def) "view" of graph.
With this fix, DF immediately detects that artifact in issue is unresolvable (just like BF does), as it contains unsolvable (not intersecting) ranges.
---
https://issues.apache.org/jira/browse/MRESOLVER-316
=> [MRESOLVER-316] DF Collector may enter endless loop

maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersion.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/version/GenericVersionTest.java
Long outstanding problem: GenericVersion since long time had issue with sorting some peculiar version strings (well, parsing them and the producing comparable Version instances to be precise). One kind of these peculiar strings are hex strings, that we even encourage should be used on this page https://maven.apache.org/maven-ci-friendly.html Problems happen, when Maven decides to sort these versions, like it happened to user using `versions-maven-plugin:set-property` that involves version sorting during version resolution https://issues.apache.org/jira/browse/MRESOLVER-314 (see stack trace). Again, this is nothing new, seems this was like it since ages, but again, we started promoting "CI friendly" not so long ago, and my guess is people started using those, and this issue will just …
=> [MRESOLVER-314] IAEx thrown when sorting versions with hex values

maven-resolver-named-locks-redisson/src/site/markdown/index.md.vm
This is not required anymore since https://github.com/apache/maven/pull/776
=> Update Named Locks w/ Redisson documentation

maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java, maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResult.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
Users get confused about artifact availability checks, and resolver should provide better error messages. Availability check is checking for (known) origin of locally cached artifact and the request repositories overlap, if none found, the artifact, despite being present locally, is not available.
Present this to end users, and educate them what is and what for is "artifact availability check".
---
https://issues.apache.org/jira/browse/MRESOLVER-333
=> [MRESOLVER-333] Better errors about artifact availability

maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/SharingHttpContext.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
Code is broken when default HTTP or HTTPS (80 or 443) ports are used, as SharedAuthCache "normalized" host will not match those of pre-set in case of preemptive auth. The UT case (non-default ports) works and is valid, as UT cannot bind ports 80 or 443.
Fix: expose AuthCache and do things "by the book".
---
https://issues.apache.org/jira/browse/MRESOLVER-339
=> [MRESOLVER-339] Preemptive auth fix

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRemoteRepositoryManager.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/StubRemoteRepositoryManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/StringUtils.java
Fwiwm `StringUtils` was deprecated since quite some time, but I'd agree that a micro release is not the best place to remove a public class.  Maybe wait for next minor...
=> [MRESOLVER-350] Inline StringUtils

pom.xml
Fixes:
* make minimalMavenBuildVersion be "[3.8.7,)", we mean "recent" or maybe "maintained" Maven version.
* make minimalJavaBuildVersion be "[1.8.0-362,)" we mean "recent" Java 8. *CI helped to decide: 362*
Note: values taken from current CI setup.
---
https://issues.apache.org/jira/browse/MRESOLVER-359
=> [MRESOLVER-359] Make build be explicit about build time requirements

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/transformer/ConflictResolverTest.java
The check was wrong, it was "has ANY sibling", while it should be "has ANY RELATED sibling".
---
https://issues.apache.org/jira/browse/MRESOLVER-357
=> [MRESOLVER-357] Fix the code to deliver the promise in comment

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultUpdateCheckManager.java
This PR does NOT make any semantic change, it literally just makes existing code self-explanatory.
Just to avoid that in 2 years another of us looks at this and become puzzled what in case of "last modified" means 0L, and why a method returns 1L, etc.
This class is fully covered with self explanatory UTs as well.
No JIRA created either.
=> Make code self explanatory

maven-resolver-connector-basic/pom.xml, maven-resolver-demos/maven-resolver-demo-snippets/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, pom.xml
Guava is not used anywhere in codebase, but as transitive dependency of Guice was "controled", but this makes no sense.
---
https://issues.apache.org/jira/browse/MRESOLVER-356
=> [MRESOLVER-356] Remove Guava

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapter.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/NamedLockFactory.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/providers/NoopNamedLockFactory.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/AdaptedSemaphoreNamedLock.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/FileLockNamedLock.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/NamedLockFactorySupport.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/NamedLockSupport.java, maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/ReadWriteLockNamedLock.java, maven-resolver-named-locks/src/site/markdown/index.md.vm, maven-resolver-named-locks/src/test/java/org/eclipse/aether/named/NamedLockFactoryTestSupport.java
The change "pulls" all `NamedLock` interface methods "level up" from implementations to `NamedLockSupport`, to be able to augment instances at `NamedLockSupport` level.
If diagnostic enabled:
* factory makes all named lock instances to gather "diag stats" (in memory!)
* on adapter failure, factory will dump out diagnostic state,
* each active lock (non closed) will dump it's state out (per thread with "steps")
* output goes to lock factory INFO logger, potentially swarming console
By default, when "diagnostic" not turned on, no change really.
---
https://issues.apache.org/jira/browse/MRESOLVER-370
=> [MRESOLVER-370] Lock factory diagnostic on failure

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
In change 4c5e9ea98f8815c6df8bf26baa9032c8d9cd5f2d we introduced code that in some case tries illegal "lock upgrade", that due lack of MRESOLVER-220 went unnoticed.
This change merely undoes the changes for DefaultArtifactResolver and DefaultMetadataResolver (will as before, use exclusive SyncContext immediately, not be "optimistic"), while change for DefaultDeploy is still correct.
---
https://issues.apache.org/jira/browse/MRESOLVER-373
=> [MRESOLVER-373] Partially undo MRESOLVER-346

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/GAVNameMapper.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/GAVNameMapperTest.java
This class currently gives away same names for artifact and metadata locks, that causes MRESOLVER-373 where artifact and metadata resolver together attempt illegal "lock upgrade", as both operate on same named lock.
This is wrong, as all other name mappers distinguish among them, also in case of snapshots, there are cases when shared lock is enough for artifact but metadata MAY need refresh, hence exclusive.
Important note: changing "naming" implies, that Maven carrying resolver with this change will be UNABLE to properly "share" local repository with older Mavens (so if this gets into Maven 3.9.3, it will properly share local repository other Maven 3.9.3+ instances, but not with 3.9.2, 3.9.1 or 3.9.0!)
---
https://issues.apache.org/jira/browse/MRESOLVER-373
=> [MRESOLVER-373] Make GavNameResolver to distinguish names better

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NameMapper.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/StaticNameMapper.java
Partially undo MRESOLVER-346: 1acec9baf6fcb8eb010d64e8009778a13a88d38e
Also, make existing "static" name mapper obey the rule (distinguish between artifacts and metadata) and make not about this on NameMapper interface as we..
---
https://issues.apache.org/jira/browse/MRESOLVER-381
=> [MRESOLVER-381] Make "happy path" shared locking again

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
Solve the mixup of Artifact used as key, as in case of relocation A1 -> A2, when A1 descriptor is read, the result will have A2 artifact set.
So, in code, we must go for "originally asked" A1 artifact, as in case of relocation, the descriptor will hold A1 relocation target, that is A2, causing endless loop.
---
https://issues.apache.org/jira/browse/MRESOLVER-376
=> [MRESOLVER-376] SOError fix for BF collector

maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegateTestSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollectorTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollectorTest.java, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTreeResult_BF.txt, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTreeResult_DF.txt, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_aid_1.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_cid_1.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_cid_2.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_cid_3.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_relocatedcid_1.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_relocatedcid_2.ini, maven-resolver-impl/src/test/resources/artifact-descriptions/transitiveDepsUseRangesAndRelocationDirtyTree_relocatedcid_3.ini, maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/IniArtifactDescriptorReader.java
This UT on master makes old DF work, while BF break with SOError.
If same UT ran on fixed branch, both pass.
Still, seems combo of range+relocation has some other issues as well, as all this works only partially, as the range is not resolved, only first applicant (lowest version in DF and highest version in BF as it sort-reverse the versions). This may be UT support class issue as well, unsure.
---
https://issues.apache.org/jira/browse/MRESOLVER-376
=> [MRESOLVER-376] UT for bug

maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-transport-http/pom.xml, pom.xml
Update dependencies:
* hazelcast 5.3.1
* redisson 3.23.2
* commons-codec 1.16.0
* maven (in demos and supplier) 3.9.4
Also, minor, but:
* remove redundant plugin assembly plugin version (redisson module, is defined in parent)
* fix demo plugin prerequisite, align with minimal maven build version
---
https://issues.apache.org/jira/browse/MRESOLVER-395
=> [MRESOLVER-395] Update dependencies, tidy up

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/StubFileTransformerManager.java, maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/IniArtifactDataReader.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/filter/PatternExclusionsDependencyFilterTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/filter/PatternInclusionsDependencyFilterTest.java
As discussed on
- https://github.com/apache/maven-scm/pull/184
- https://issues.apache.org/jira/browse/MNG-6847
Review requested of @elharo
Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.staticanalysis.UseDiamondOperator?organizationId=QXBhY2hlIE1hdmVu
=> [MNG-6847] Use diamond operator

maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/AetherModule.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/guice/package-info.java
Lowering the provided instantiation support from 3 to 2, to lower resources for maintenance all these.
SL is about to be dropped, Guice same. Users should either use Sisu or use the new Supplier.
---
https://issues.apache.org/jira/browse/MRESOLVER-397
=> [MRESOLVER-397] Deprecate Guice integration

maven-resolver-transport-http/pom.xml
The older versions trigger nasty CVE reports. No real effect, as this is really just a test dependency.
---
https://issues.apache.org/jira/browse/MRESOLVER-406
=> [MRESOLVER-406] Update Jetty to 9.4.52.v20230823

maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, pom.xml, src/site/markdown/third-party-integrations.md
And get rid of deprecations (no-arg ctors) and string literals.
=> Update to Maven 3.9.5

.github/workflows/maven-verify.yml, Jenkinsfile, maven-resolver-api/pom.xml, maven-resolver-connector-basic/pom.xml, maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, maven-resolver-demos/maven-resolver-demo-snippets/pom.xml, maven-resolver-demos/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-named-locks/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-supplier/pom.xml, maven-resolver-test-util/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, maven-resolver-util/pom.xml, pom.xml, src/site/markdown/resolver-major-version-migration.md, src/site/markdown/upgrading-resolver.md, src/site/site.xml
Changes:
* make version 2.0.0-SNAPSHOT
* build time JDK requirement: raise to 11 (raise as needed, preferably use LTS versions)
* existing modules are `release=8`
* drop animal sniffer
* redefine enforceBytecodeVersion: we do produce Java 8 stuff, but for **testing** we may want and will want to use something that is 8+ (ie. Jetty 12)
* fix sisu (was invoked twice, last parent POM update)
* compiler: proactively disable annotation processing (we do not use those, but Sisu APT is present, we do not want it auto-picked up, we explicitly index using sisu mojo)
* compiler: be chatty about deprecations, to help us down the line removing them
---
https://issues.apache.org/jira/browse/MRESOLVER-408
=> [MRESOLVER-408] Make master 2.0.0-SNAPSHOT

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/DefaultRemoteRepositoryFilterManager.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporterFactory.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
Now the last bit remaining is ChecksumUtils that is to be handled in different issue. This PR merely removes all the compiler warnings about deprecation but ChecksumUtils.
---
https://issues.apache.org/jira/browse/MRESOLVER-409
=> [MRESOLVER-409] More deprecation removal

maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalRepositoryProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryLayoutProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTransporterProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/PrioritizedComponents.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Utils.java, src/site/markdown/configuration.md
Cache them, as creating of those is not cheap, but detect (dynamic injected) map changes. Allow users to disable this feature, in case of fire.
---
https://issues.apache.org/jira/browse/MRESOLVER-420
=> [MRESOLVER-420] Cache prioritized components

maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, pom.xml
And get rid of last TODO. Note: this issue is refurbished from "Update to Maven 4.0.0-alpha-7".
---
https://issues.apache.org/jira/browse/MRESOLVER-411
=> [MRESOLVER-411] Update to Maven 4.0.0-alpha-8

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultInstallerTest.java
Still, make possible to restore the "skip if missing" as I find no reasonong for it, but my guess is that it may be about some legacy code somewhere, most probably adding Metadata without backing file (as in Maven2 metadata was added by hand).
---
https://issues.apache.org/jira/browse/MRESOLVER-392
=> [MRESOLVER-392] Remove change detection logic on install

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/DependencyGraphDumper.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/visitor/DependencyGraphDumperTest.java
Make graph dumper extensible, as it is meant to be reusable, but not everyone may want same info on output. Also, most of the methods were private...
---
https://issues.apache.org/jira/browse/MRESOLVER-424
=> [MRESOLVER-424] Make graph dumper extensible

.github/workflows/maven-verify.yml, Jenkinsfile, pom.xml
Actually, 21.0.1 as 21 had a bug that one of two needed preconditions are always met in case of Maven (m-compiler-p always sets debug=true).
---
https://issues.apache.org/jira/browse/MRESOLVER-430
=> [MRESOLVER-430] Build time Java 21 required

maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-19/pom.xml, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-21/pom.xml, pom.xml
Not much to fix really, but simply put the "minimally required Java" and Javadoc URL needs to be kept in sync. But, as former is a range, latter is a "base version", it goes only manually.
Hence, I left a note in POM for this.
Site related fixes:
* Javadoc craps out on 19 and 21 JDK transport modules (nothing to document).
* PMD does not supports Java 21.
---
https://issues.apache.org/jira/browse/MRESOLVER-422
=> [MRESOLVER-422] Fix javadoc configuration

maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystemSession.java, maven-resolver-api/src/main/java/org/eclipse/aether/repository/AuthenticationContext.java, maven-resolver-impl/src/main/java/org/eclipse/aether/impl/RepositorySystemLifecycle.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystemLifecycle.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/session/DefaultCloseableSession.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/session/DefaultSessionBuilder.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/ChainedLocalRepositoryManager.java, pom.xml, src/site/markdown/configuration.md
Changes:
* rename closeable session to lessen repetition in source
* defer creation of LRM to ctor of DefaultCloseableSession
* support chained LRM out of the box
* make AuthenticationContext not need session (as it does not use it directly)
---
https://issues.apache.org/jira/browse/MRESOLVER-302
=> [MRESOLVER-302] Addendum

maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkHttpTransporter.java, src/site/markdown/configuration.md
Add configuration to inhibit expect/continue handshake. Currently supported by "apache" and "jdk" HTTP transports.
---
https://issues.apache.org/jira/browse/MRESOLVER-427
=> [MRESOLVER-427] Config for expect/continue inhibition

maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java, src/site/markdown/configuration.md
Add configuration to inhibit expect/continue handshake.
---
https://issues.apache.org/jira/browse/MRESOLVER-433
Backport of relevants parts from this commit: https://github.com/apache/maven-resolver/commit/178cfba9f3889f7e942a6a0d74716355b01a78f5
=> [MRESOLVER-433] Config for expect/continue inhibition (#363)

maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
Fixes:
* move() call should NOT perform the move, as writer stream to tmp file may still be open
* move the file move logic to close, make it happen only when closing collocated temp file
* perform fsync before atomic move to ensure there is no OS dirty buffers related to newly written file
* on windows go with old code that for some reason works (avoid NIO2)
* on non-Win OS fsync the parent directory as well.
So, to recap:
* original issue is not related to locking at all, is about change done in 1.9 where file processor was altered to use nio2 atomic move (to prevent possibility of partial download being read by other process and prevent incomplete files in case of crash).  Maven LRM uses layout, so randomized temp files does not matter (if they remain after crash), as they would merely …
=> [MRESOLVER-372] Rework the FileUtils collocated temp file

maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, src/site/markdown/configuration.md
Backport of MRESOLVER-437 to 1.9.x branch (only relevant parts): 
https://github.com/apache/maven-resolver/commit/a70ddef13490a4289e4a72327217218e688e4070
---
https://issues.apache.org/jira/browse/MRESOLVER-437
=> [MRESOLVER-437] Resolver should not override given HTTP transport default use of expect-continue handshake

maven-resolver-transport-jdk/pom.xml, maven-resolver-transport-jdk/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java, maven-resolver-transport-jdk/src/test/java/org/eclipse/aether/transport/jdk/JdkTransporterTest.java
By default HTTP Client is quite muted, message is "ConnectException". As this "message enhancement" already happens on a branch that leads to error, the throwing of new exception and "decorating it" really does not matter, as the end result is anyway: resolver invocation failure (in Maven is build failure).
---
https://issues.apache.org/jira/browse/MRESOLVER-429
=> [MRESOLVER-429] Emit more informative message on connection refused

maven-resolver-api/src/main/java/org/eclipse/aether/graph/DefaultDependencyNode.java, maven-resolver-api/src/test/java/org/eclipse/aether/graph/DefaultDependencyNodeTest.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegateTestSupport.java
Currently the two collector implementations are not interrupt-able, do not sense interruption directly, only by some side-effect like IO. Moreover, the BF new collector may enter a "busy loop" as we seen (it was due bug, but nothing prevents us to have more bugs). Make main loop in both collector detect thread interruption and use global (per-collection) Args to carry state of the, interruption effectively the whole ST or MT collection.
Same stands for dependency visitor: it may also enter busy loop in case of cycles, hence, it should be made also  interrupt-able. Visitor OTOH should not reset the interrupted flag, it should just stop when it is set, and let the flag be handled at higher level (for example in collector).
---
https://issues.apache.org/jira/browse/MRESOLVER-321
=> [MRESOLVER-321] Make collection and visiting interruptable

maven-resolver-demos/maven-resolver-demo-snippets/pom.xml, maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/supplier/SupplierRepositorySystemFactory.java, maven-resolver-supplier/pom.xml, maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, pom.xml
Seems the "atypical" modules like supplier and
demo snippets were completely omitted from the
transport rename, and were still using renamed
transport-http instead the new transport-apache.
---
https://issues.apache.org/jira/browse/MRESOLVER-440
=> [MRESOLVER-440] Addendum

maven-resolver-api/src/test/java/org/eclipse/aether/DefaultRepositoryCacheTest.java, maven-resolver-api/src/test/java/org/eclipse/aether/DefaultRepositorySystemSessionTest.java, maven-resolver-api/src/test/java/org/eclipse/aether/repository/AuthenticationContextTest.java, maven-resolver-api/src/test/java/org/eclipse/aether/repository/AuthenticationDigestTest.java, maven-resolver-api/src/test/java/org/eclipse/aether/transfer/TransferEventTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultOfflineControllerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DataPoolTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DefaultVersionFilterContextTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/transformer/AbstractDependencyGraphTransformerTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/ComponentAuthenticationTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/JreProxySelectorTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/SecretAuthenticationTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/StringAuthenticationTest.java
With latest changes there were some deprecations, most notably the default ctor of DRSS. Due that the build started emitting quite some warning messages during build.
This is now lowered to 2 warnings for whole build. There is no issue for this, as these changes are all happening in UTs.
=> Update UTs regarding deprecations

maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystem.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
As this now exposes full "third step" in resolveDependencies, so client code can reuse and have all of it.
---
https://issues.apache.org/jira/browse/MRESOLVER-447
=> [MRESOLVER-447] Expose flatten method w/ filter

maven-resolver-tools/pom.xml
Simply invoke it as very last step of build to generate the documentation. Ideally, this will produce _same output_ hence there will be no side effect (no local change). But in case page is outdated (needs update) the local checkout becomes dirty and would prevent release for example.
This is not "final" solution, but would work IMHO. Current issue with tool is that:
* it must have access to up-to-date class files (to javap them), hence it runs as last module of multi module build
* it must process WHOLE project, so to say "aggregate" output, it cannot run per module
---
https://issues.apache.org/jira/browse/MRESOLVER-443
=> [MRESOLVER-443] Integrate tool into build

maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositoryCache.java, maven-resolver-api/src/main/java/org/eclipse/aether/RepositoryCache.java, pom.xml
Enhance RepositoryCache
---
https://issues.apache.org/jira/browse/MRESOLVER-450
=> [MRESOLVER-450] Enhance RepositoryCache

maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
Undo most of the changes to ArtifactResolutionException, as Maven Core depends on it's logic (is flawed for message, but is not to drive logic by checking cause).
Previos main PR did expose all the needed things anyway, so basically it is now Maven turn to instead reusing the (flawed) message to emit it to end user/console, build some better message using new methods.
---
https://issues.apache.org/jira/browse/MRESOLVER-335
=> [MRESOLVER-335] Proposal for better errors (addendum)

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/ChainedVersionFilter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/ContextualSnapshotVersionFilter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/LowestVersionFilter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/PredicateVersionFilter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/SnapshotVersionFilter.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/versions/LowestVersionFilterTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/versions/PredicateVersionFilterTest.java
Tidy up the classes and add "lowest" and "predicate" filter as well. For "exposing" not much needed, is rather client stuff to do: set it on session.
---
https://issues.apache.org/jira/browse/MRESOLVER-451
=> [MRESOLVER-451] Tidy up version filters

maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionConstraint.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionRange.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionScheme.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/VersionSchemeSupport.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/version/GenericVersionRangeTest.java
Since eons Resolver had the "generic" scheme implementing the `Version`, `VersionRange` and `VersionConstraint` API interfaces.
Interesting fact: `GenericVersionRange` and `GenericVersionConstraint` are NOT tied in any way to `GenericVersion` implementation, they are happy with plain `Version` interface as well, they are truly "generic".
This means, that a scheme needs really only to provide `Version` implementation (currently in form of `GenericVersion`) and a "factory" for it (currently in a form of `GenericVersionScheme`).
Refactor a bit, and make room for alternate Version implementations.
Fact: the change can be done in source and binary compatible way, and is enforced by japicmp.
---
https://issues.apache.org/jira/browse/MRESOLVER-465
=> [MRESOLVER-465] Make room for alternate version scheme

src/site/markdown/common-misconceptions.md, src/site/markdown/expected-checksums.md, src/site/markdown/remote-repository-filtering.md, src/site/site.xml
Site updates, adding new page.
---
https://issues.apache.org/jira/browse/MRESOLVER-466
=> [MRESOLVER-466] Site documentation updates

maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/SessionBuilderSupplier.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/artifact/JavaScopes.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/artifact/Scopes.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/filter/DependencyFilterUtils.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/AbstractDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/JavaDependencyContextRefiner.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/JavaScopeDeriver.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/JavaScopeSelector.java
In Resolver 1.x it defined scopes (that were redefined by consumer project Maven), leading to duplication and possible digression if Maven was about to support new dependency scopes. Moreover, Resolver 1.x also contained (based on these scopes) logic, "scope refinement", "scope derive to buildpath scope" and so on. All these logic just like the definition of scopes belong to consumer project: Maven.
Resolver really cares about only one scope: "system", as dependencies in this scope should be handled very differently than others (have no POMs and just file presence should be checked on resolving them).
---
https://issues.apache.org/jira/browse/MRESOLVER-471
=> [MRESOLVER-471] Resolver should be oblivious about scopes.

pom.xml
Client used for "jetty" transport, and Server used in HTTP tests.
Release notes:
https://github.com/jetty/jetty.project/releases/tag/jetty-11.0.19
---
https://issues.apache.org/jira/browse/MRESOLVER-472
=> [MRESOLVER-472] Update Jetty 10.0.19

maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-8/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterFactory.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk/pom.xml, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/package-info.java
Changes:
* Javadoc issue: use of H1 HTML tag in versions package javadoc
* Non aligned ctor of JDK Transport factory
* use proper m-dependency-p:unpack-dependencies goal
=> Fixes for release

maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegateTestSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfWithSkipperDependencyCollectorTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/artifact/DependencyScopes.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/SystemScopePredicate.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/AbstractDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/ClassicDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/DefaultDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/TransitiveDependencyManager.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/manager/DependencyManagerTest.java
It is duty of consumer application to define those. Also, no need for SPI either, as essentialy ONLY the dependency managers were using the "system" scope definition so far.
Now, client code, that instantianates these anyway are able to pass in predicate.
Note: as util is japicmp checked, the def ctors MUST stay, but are deprecated.
---
https://issues.apache.org/jira/browse/MRESOLVER-491
=> [MRESOLVER-491] Resolver should not have any "predefined" scope

maven-resolver-api/src/main/java/org/eclipse/aether/artifact/AbstractArtifact.java
In cases when AbstractArtifact was extended, the
getPath method would go missing.
---
https://issues.apache.org/jira/browse/MRESOLVER-515
=> [MRESOLVER-515] Restore binary compatibility

maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/FileLockNamedLock.java
Instead to immediately give up and sleep, they will sit a while to enter critical region. This is important for "hot" locks.
Explanation: currently a "loser" will _immediately give up_ and will go to sleep 100ms if cannot enter critical region, even if winner exits critical region within next 5ms. The retry is needed to ensure that it is retried as much as given time/unit takes, that was before consumed by constant retries+sleeps. The logic still works, as if tryLock spends time/unit waiting on criticalRegion (which is possible only on VERY HIGHLY congested locks), there will be no retry happening.
---
https://issues.apache.org/jira/browse/MRESOLVER-521
=> [MRESOLVER-521] Improve congested file locks behaviour

maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/FileLockNamedLock.java
Instead to immediately give up and sleep, they will sit a while to enter critical region. This is important for "hot" locks.
Explanation: currently a "loser" will _immediately give up_ and will go to sleep 100ms if cannot enter critical region, even if winner exits critical region within next 5ms. The retry is needed to ensure that it is retried as much as given time/unit takes, that was before consumed by constant retries+sleeps. The logic still works, as if tryLock spends time/unit waiting on criticalRegion (which is possible only on VERY HIGHLY congested locks), there will be no retry happening.
Backport of 089796ba66d6f5f1a9d4fa7f797f613bae4f5373
---
https://issues.apache.org/jira/browse/MRESOLVER-522
=> [1.9.x] [MRESOLVER-522] Improve congested file locks behaviour (#455)

maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-transport-http/pom.xml, pom.xml
Changes:
* hazelcast 5.3.7
* redisson 3.28.0
* commons-codec 1.16.1
* sisu 0.9.0.M2
* guice 6.0.0 (and guava 33.1.0)
* jetty 9.4.54 (used in tests)
* maven 3.9.6 (used in demos)
---
https://issues.apache.org/jira/browse/MRESOLVER-527
https://issues.apache.org/jira/browse/MRESOLVER-528
https://issues.apache.org/jira/browse/MRESOLVER-529
https://issues.apache.org/jira/browse/MRESOLVER-530
https://issues.apache.org/jira/browse/MRESOLVER-531
https://issues.apache.org/jira/browse/MRESOLVER-532
https://issues.apache.org/jira/browse/MRESOLVER-533
=> [1.9.x] Update dependencies

maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java
This seems more logical step, simply use File.setLastModified as it does not throws, and is used all over the 1.9.x codebase.
---
https://issues.apache.org/jira/browse/MRESOLVER-536
=> [1.9.x] [MRESOLVER-536] Do not belly up if FS does not support setting mtime

maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/supplier/SupplierRepositorySystemFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultPathProcessor.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/io/PathProcessor.java, maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestPathProcessor.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporter.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporterFactory.java, maven-resolver-transport-apache/src/test/java/org/eclipse/aether/transport/apache/ApacheTransporterTest.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java, maven-resolver-transport-jetty/src/main/java/org/eclipse/aether/transport/jetty/JettyTransporter.java, maven-resolver-transport-jetty/src/main/java/org/eclipse/aether/transport/jetty/JettyTransporterFactory.java, maven-resolver-transport-jetty/src/test/java/org/eclipse/aether/transport/jetty/JettyTransporterTest.java
Centralize method and apply some common logic.
---
https://issues.apache.org/jira/browse/MRESOLVER-536
=> [MRESOLVER-536] Cleanup redundancy and support FS without TS support

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultPathProcessor.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/io/PathProcessor.java, maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestPathProcessor.java
Do not swallow cases like AccessDeniedEx, and log failures. Make new method `void` as nothing is interested in return value, while all we wanted (swallow some and log) is handled here.
This PR builds upon prev PR https://github.com/apache/maven-resolver/pull/468
---
https://issues.apache.org/jira/browse/MRESOLVER-536
=> [MRESOLVER-536] Followup change: log failures

maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/GetDependencyHierarchy.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/DependencyGraphDumper.java
Ability to pass in any function that is able to "decorate" the print out of the graph. This should have a follow up Pr that enable/disable (or simply move all into decorators). Also, verbose tree should show use of version ranges, for cases when someone wants to detect them in whole transitive hull.
---
https://issues.apache.org/jira/browse/MRESOLVER-535
https://issues.apache.org/jira/browse/MRESOLVER-538
=> [MRESOLVER-535][MRESOLVER-538] Add decorator ability to graph dumper; show ranges

maven-resolver-api/src/main/java/org/eclipse/aether/transfer/TransferResource.java, maven-resolver-api/src/test/java/org/eclipse/aether/transfer/TransferEventTest.java, maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultChecksumPolicyProviderTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/FailChecksumPolicyTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/RecordingRepositoryConnector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/WarnChecksumPolicyTest.java
Provide extra information about the resource being transferred.
---
https://issues.apache.org/jira/browse/MRESOLVER-540
=> [MRESOLVER-540] TransferResource can reveal more about resource

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
No need for full copy, Artifact is already immutable. Moreover, the instance may be not DefaultArtifact but something else. And finally, setVersion already have "optimization" to return this if version is same as the one we want to copy with.
---
https://issues.apache.org/jira/browse/MRESOLVER-547
=> [MRESOLVER-547] Just use setVersion

src/site/markdown/about-checksums.md, src/site/markdown/creating-a-repository-system-session.md, src/site/markdown/dependency-graph.md, src/site/markdown/resolving-dependencies.md, src/site/markdown/transitive-dependency-resolution.md, src/site/markdown/using-resolver-in-maven-plugins.md, src/site/markdown/what-is-resolver.md, src/site/site.xml
With applied updates for Resolver 2.0.
Reworked side menu:
* Overview (as before)
* Guides (added)
* Reference (added)
* See also (as before)
---
https://issues.apache.org/jira/browse/MRESOLVER-526
https://issues.apache.org/jira/browse/MRESOLVER-289
Content from EOLd Eclipse wiki https://wiki.eclipse.org/Aether The dump is attached to MRESOLVER-526 but is filtered (outdated pages omitted) as explained on issue.
=> [MRESOLVER-526] Reuse relevant bits from Eclipse Aether wiki contents

maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositorySystemSession.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/session/DefaultSessionBuilder.java
Rename classes to reflect what they are. These are "default implementations" used on new Session instances but usually not used in "real world".
---
https://issues.apache.org/jira/browse/MRESOLVER-565
=> [MRESOLVER-565] Class renames

maven-resolver-api/pom.xml, maven-resolver-connector-basic/pom.xml, maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, maven-resolver-demos/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-named-locks/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-supplier/pom.xml, maven-resolver-test-util/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-http/pom.xml, maven-resolver-transport-wagon/pom.xml, maven-resolver-util/pom.xml, pom.xml
Keep the 'bnd' configuration for the `bnd-maven-plugin` at plugin level to simplify overwrites in sub-modules (avoid the need to re-specify the execution there).
Additionally update to `bnd-maven-plugin` 6.4.0.
If this would be applied before https://github.com/apache/maven-resolver/pull/505, it would reduce the 'noise' in that commit due to necessary re-configuraiton.
@cstamas and @gnodet if you think this change is fine, I can also forward port it to master. I also left out a JIRA ticket for such non-functional 'clean-up', let me know if it is still necessary.
=> [Build] Unify bnd-maven-plugin and maven-jar-plugin invocations

maven-resolver-api/pom.xml, maven-resolver-connector-basic/pom.xml, maven-resolver-demos/maven-resolver-demo-maven-plugin/pom.xml, maven-resolver-demos/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-named-locks/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-supplier-mvn4/pom.xml, maven-resolver-test-util/pom.xml, maven-resolver-transport-apache/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-wagon/pom.xml, maven-resolver-util/pom.xml, pom.xml
=> [Build] Unify bnd-maven-plugin and maven-jar-plugin invocations (#509)

maven-resolver-api/pom.xml, maven-resolver-connector-basic/pom.xml, maven-resolver-generator-gnupg/pom.xml, maven-resolver-impl/pom.xml, maven-resolver-named-locks-hazelcast/pom.xml, maven-resolver-named-locks-redisson/pom.xml, maven-resolver-named-locks/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-supplier-mvn3/pom.xml, maven-resolver-supplier-mvn4/pom.xml, maven-resolver-test-http/pom.xml, maven-resolver-test-util/pom.xml, maven-resolver-tools/pom.xml, maven-resolver-transport-apache/pom.xml, maven-resolver-transport-classpath/pom.xml, maven-resolver-transport-file/pom.xml, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/pom.xml, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-21/pom.xml, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-8/pom.xml, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk/pom.xml, maven-resolver-transport-jetty/pom.xml, maven-resolver-transport-wagon/pom.xml, maven-resolver-util/pom.xml, pom.xml
and derive 'Bundle-SymbolicName' header from the artifactId where possible.
This is originally created for https://github.com/apache/maven-resolver/pull/516, but would probably also make https://github.com/apache/maven-resolver/pull/506 simpler.
=> [Build] Define all MANIFEST.MF entries through the bnd-maven-plugin

pom.xml
- Mark optional Maven dependencies as optional in OSGi metadata
- Widen version range for org.slf4j.spi package to [1.7,3)
- Move bnd configuration section from execution to plugin configuration in order to simplify extensions in sub-modules.
This is a forward port of https://github.com/apache/maven-resolver/pull/505 to resolver-2.x/master, that skips the update of the bnd-maven-plugin since it is already at 7.0.0.
Fixes [MRESOLVER-570](https://issues.apache.org/jira/browse/MRESOLVER-570)
=> [MRESOLVER-570] Remove excessive strictness of OSGi dependency metadata

maven-resolver-api/pom.xml, maven-resolver-spi/pom.xml, maven-resolver-util/pom.xml
This PR has the same intend as https://github.com/apache/maven-resolver/pull/508, but uses the `bnd-maven-plugin` to generate the `module-info.class` automatically using the `-jpms-module-info` instruction:
https://bnd.bndtools.org/releases/6.4.0/chapters/330-jpms.html
The differences to #508 are that the source `module-info.java` is not generated and that the `module-info.class` is always placed in the jar root. But since JRE's below Java-9 don't recognize that file, I hope that's not a problem.
=> [MRESOLVER-27] Turn resolver api, spi and utils into Java 9 modules with generated module-info.class

pom.xml
This is a forward-port of https://github.com/apache/maven-resolver/pull/510 to master.
___
This makes maven-resolver-supplier usable as bundle in an OSGi runtime. At the moment the bundle cannot resolve because the internal.impl packages it uses and imports in its OSGi metadata are not exported by maven-resolver-impl.
Simply exporting internal packages fixes that and, although it is discouraged to use internal/impl packages, gives consumers that can accept no API-compatibility guarantees the ability to access these packages.
Adding the directive 'x-internal' is a convention that, at least when using Eclipse PDE, shows a corresponding warning at call-sides.
Fixes https://issues.apache.org/jira/browse/MRESOLVER-572
=> [MRESOLVER-572] Export internal packages in OSGi metadata as x-internal

maven-resolver-impl/pom.xml, pom.xml
- Mark optional Maven dependencies as optional in OSGi metadata
It is an explicit decision from bndtools to require explicit configuration of a user to make a dependency optional, even if the corresponding maven dependency is optional: https://github.com/bndtools/bnd/issues/2713
- Widen version range for org.slf4j.spi package to [1.7,3)
Fixes [MRESOLVER-570](https://issues.apache.org/jira/browse/MRESOLVER-570)
=> [1.9.x] [MRESOLVER-570] Remove excessive strictness of OSGi dependency metadata

pom.xml
This makes maven-resolver-supplier usable as bundle in an OSGi runtime.
At the moment the bundle cannot resolve because the `internal.impl` packages it uses and imports in its OSGi metadata are not exported by `maven-resolver-impl`.
Just exporting internal packages fixes that and, although it is discouraged to use internal/impl packages, gives consumers that can
accept no API-compatibility guarantees the ability to access these packages.
Adding the directive `x-internal` is a convention that, at least when using Eclipse PDE, shows a corresponding warning at call-sides.
Fixes https://issues.apache.org/jira/browse/MRESOLVER-572
This PR is currently a draft since it contains as first commit the build unification of https://github.com/apache/maven-resolver/pull/509 and is built on top of …
=> [1.9.x] [MRESOLVER-572] Export internal packages in OSGi metadata as x-internal

pom.xml
This is a forward-port of https://github.com/apache/maven-resolver/pull/507 to the master branch.
___
The documentation states that only maven-resolver artifacts of the exact same version should be used together.
With this change all org.eclipse.aether* packages are now imported with a strict version range of
'org.eclipse.aether*;version="[@version,@version]"'
Fixes https://issues.apache.org/jira/browse/MRESOLVER-571
=> [MRESOLVER-571] Import o.e.aether packages with the exact same version

maven-resolver-impl/pom.xml, pom.xml
The documentation states that only maven-resolver artifacts of the exact same version should be used together.
With this change all `org.eclipse.aether*` packages are now imported with a strict version range of
`'org.eclipse.aether*;version="[@version,@version]"'
`
Fixes https://issues.apache.org/jira/browse/MRESOLVER-571
This PR currently also containes the changes planned for https://github.com/apache/maven-resolver/pull/505.
If there is agreement for this change, I'll forward port it to the `master/2.x`.
=> [1.9.x] [MRESOLVER-571] Import o.e.aether packages with the exact same version

pom.xml
To keep things simple, we config the plugin in
one place, but in some modules this config emits
warnings. This change just makes it go away.
No other source or any alike change, no issue either.
=> Tame bnd plugin warnings

pom.xml
To keep things simple, we config the plugin in
one place, but in some modules this config emits
warnings. This change just makes it go away.
No other source or any alike change, no issue either.
=> [1.9.x] Tame bnd plugin warnings

maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java
I have been experimenting with Maven 4.0.0-beta-4, specifically testing its HTTP/2 support. During my tests, I used a self-signed certificate for the testing repository and disabled TLS validation. This approach produced unexpected behavior. While TLS certificate validation was indeed disabled as expected, it also caused the ALPN extension to be omitted from the Client Hello message.
To further investigate, I added the self-signed certificate to the JDK's cacerts keystore and removed the insecure option. With this configuration, ALPN support was restored, and HTTP/2 worked correctly again. This behavior can lead to problems if the server prioritizes HTTP/2 or does not support HTTP/1.1.
This change addresses an issue where SSLParameters were being overwritten (introduced in …
=> [MRESOLVER-579] Fix overwrite of SSLParameters in JDK HTTP transport when securityMode is "insecure"

maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpServer.java, maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpTransporterTest.java, maven-resolver-transport-apache/src/test/java/org/eclipse/aether/transport/apache/ApacheTransporterTest.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java
Adds tests, as with new test:
* JDK transport fails as user explained
* Jetty behaves
* Apache is not HTTP2 capable
---
https://issues.apache.org/jira/browse/MRESOLVER-579
=> [MRESOLVER-579] The TODO part

maven-resolver-api/src/main/java/org/eclipse/aether/artifact/DefaultArtifact.java
When we don't have specific properties for a DefaultArtifact, we can just reuse the type default properties map as it's readonly and immutable.
The patch contains some additional changes as I renamed the method and parameters to make them more specific so that the method wouldn't be used for things that wouldn't be safe.
=> [MRESOLVER-586] Avoid copying the type default properties map

maven-resolver-api/src/main/java/org/eclipse/aether/artifact/DefaultArtifact.java
> [!NOTE]
> I needed a backport for my internal testing and it wasn't clean so here it is.
When we don't have specific properties for a DefaultArtifact, we can just reuse the type default properties map as it's readonly and immutable.
The patch contains some additional changes as I renamed the method and parameters to make them more specific so that the method wouldn't be used for things that wouldn't be safe.
=> [MRESOLVER-586] Avoid copying the type default properties map - 1.9.x

maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystemSession.java
This method is NOT the "usual" way to introduce new LRM implementation. LRM is special in a sense, is needed early. Proper way is to integrate with LRMProvider instead and tune priorities and/or LocalRepository type strings.
---
https://issues.apache.org/jira/browse/MRESOLVER-585
=> [MRESOLVER-585] Explain reason for this method

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DataPoolTest.java
Do not use `Object` as descriptor key, use dedicated type. And intern the `List<Dependency>` on artifact descriptors. Also introduce "intern"-ing of ArtifactDescriptor dependencies and managedDependencies that is configurable (speed vs memory).
---
https://issues.apache.org/jira/browse/MRESOLVER-587
=> [MRESOLVER-587] Memory usage improvements

maven-resolver-transport-jetty/src/main/java/org/eclipse/aether/transport/jetty/JettyTransporter.java
Just shorten the client lifespan to connector transaction duration vs as before, for whole session duration. Also simplify the code.
---
https://issues.apache.org/jira/browse/MRESOLVER-584
=> [MRESOLVER-584] Jetty transport HTTP/2 GOAWAY improvement

maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystem.java, maven-resolver-api/src/main/java/org/eclipse/aether/artifact/Artifact.java, maven-resolver-api/src/main/java/org/eclipse/aether/artifact/DefaultArtifact.java
Point out that the exact syntax of a version depends on the underlying provider
=> [MRESOLVER-598] Improve Javadoc on version ranges

pom.xml
It does not matter, but I dislike to pull in alpha of Maven 4 (Resolver should not pull anything of
Maven only in demos).
---
Undo https://issues.apache.org/jira/browse/MRESOLVER-619
=> Undo P-X raise

maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporter.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/test/java/org/eclipse/aether/transport/jdk/JdkTransporterTest.java, maven-resolver-transport-jetty/src/main/java/org/eclipse/aether/transport/jetty/JettyTransporter.java
The `ConfigurationProperties#REQUEST_TIMEOUT` was wrongly interpreted by JDK and Jetty clients as "absolute max duration of HTTP request".
Also, up default CONNECT_TIMEOUT from 10sec to 30sec.
Changes per transport:
* apache: explain meaning in comments and fix one mixed up timeout
* JDK: remove use of request timeout (as it means "abs max time for request"), note that REQUEST_TIMEOUT is not supported, ignore UT
* Jetty: remove use of request timeout (as it means "abs max time for request"), use "idle timeout" that means "max time of silence between any traffic/sending or receiving packets".
---
https://issues.apache.org/jira/browse/MRESOLVER-612
https://issues.apache.org/jira/browse/MRESOLVER-615
=> [MRESOLVER-612] Align timeout interpretations across HTTP transports

maven-resolver-tools/pom.xml
The maven-resolver-tools was not deployed before 2.0.3, and in 2.0.3 release had to manually add sigs for the two new files.
This is simple fix just by reordering generation/attach of the files to let gpg plugin sign them as well.
=> Fix deployment

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/AbstractDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/ClassicDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/DefaultDependencyManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/TransitiveDependencyManager.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/manager/DependencyManagerTest.java
Undo original "clic-clac" solution introduced in first PR, instead, we need more fine-grained control of what and when is applied.
---
https://issues.apache.org/jira/browse/MRESOLVER-614
=> [MRESOLVER-614] Fix transitive dependency management

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalRepositoryProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryLayoutProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTransporterProvider.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/PrioritizedComponents.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Utils.java
As original solution using map.hashCode may clash, and in that case runtime "just in time" class clast issue happens.
Rather provide explicit discriminator class "what is in maps" and use that to create key to cache in session.
---
https://issues.apache.org/jira/browse/MRESOLVER-628
=> [MRESOLVER-628] Explicit cache key for prioritized components

src/site/markdown/using-resolver-in-maven-plugins.md
=> Update to 1.9.22

maven-resolver-api/pom.xml, maven-resolver-api/src/main/java/org/eclipse/aether/transfer/TransferResource.java, maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ConsoleTransferListener.java
This also provides a clean for Maven to inject the `MonotonicClock` from https://github.com/apache/maven/pull/1965
---
https://issues.apache.org/jira/browse/MRESOLVER-635
=> [MRESOLVER-635] Use Instant instead of untyped millis for TransferResource startTime

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultDeployerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultInstallerTest.java, maven-resolver-spi/src/main/java/org/eclipse/aether/spi/artifact/transformer/ArtifactTransformer.java, maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
A SPI for artifact install/deploy request transformation.
---
https://issues.apache.org/jira/browse/MRESOLVER-644
=> [MRESOLVER-644] Artifact Transformer SPI

maven-resolver-api/src/main/java/org/eclipse/aether/repository/LocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManager.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/ChainedLocalRepositoryManager.java
Pull in repeated snippets under LRM.
---
https://issues.apache.org/jira/browse/MRESOLVER-645
=> [MRESOLVER-645] Remove repeated LRM interaction

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessor.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java
Obvious typo: result artifact may be null, it is request artifact that wanted to be checked.
---
https://issues.apache.org/jira/browse/MRESOLVER-653
=> [MRESOLVER-653] NPE in case of failed result

src/site/markdown/local-repository.md
Just add explanation how properties are renamed, but not change needed, as MRESOLVER-652 adds backward compat support.
---
https://issues.apache.org/jira/browse/MRESOLVER-651
=> [MRESOLVER-651] Doco update re split repo

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactorySupport.java
Added legacy properties for now as private and undocumented keys.
---
https://issues.apache.org/jira/browse/MRESOLVER-652
=> [MRESOLVER-652] Support legacy 1.9.x split repository config

maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersion.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/package-info.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/version/GenericVersionTest.java, pom.xml
Everything else is treated alphabetically.
=> ASCII digits only for versions

maven-resolver-generator-sigstore/src/main/java/org/eclipse/aether/generator/sigstore/SigstoreSignatureArtifactGenerator.java
Seems sigstore depends on TCCL that went unnoticed in test, but explodes when this generator used as Maven extension.
---
https://issues.apache.org/jira/browse/MRESOLVER-681
=> [MRESOLVER-681] Sigstore TCCL bugfix

maven-resolver-api/src/main/java/org/eclipse/aether/collection/DependencyCollectionException.java, maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactDescriptorException.java, maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java, maven-resolver-api/src/main/java/org/eclipse/aether/resolution/VersionRangeResolutionException.java, maven-resolver-api/src/main/java/org/eclipse/aether/resolution/VersionResolutionException.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
Pass on received exceptions as suppressed. Resolver was conceived when no suppressed exceptions existed and does not make use of them at all. This PR leaves existing "cause" management intact, but passes the whole tree (even for notorious `ArtifactResolutionException`) the full tree as suppressed exceptions. 
This implies that old code can still make use of existing logic to create the (incomplete) error messages, while new code can get all the needed information by walking and including suppressed exceptions as well. Logic is: if there is suppressed (and is same instance as cause or cause is null), then the given cause, if any, is "just the first out of many suppressed", hence suppressed "prevails" the cause. In that case code needs to "follow" suppressed ones.
Example: created a POM …
=> [MRESOLVER-569] Pass on exceptions

maven-resolver-transport-file/README.md, maven-resolver-transport-file/src/main/java/org/eclipse/aether/transport/file/FileTransporter.java, maven-resolver-transport-file/src/main/java/org/eclipse/aether/transport/file/FileTransporterFactory.java, maven-resolver-transport-file/src/main/java/org/eclipse/aether/transport/file/package-info.java, maven-resolver-transport-file/src/test/java/org/eclipse/aether/transport/file/FileTransporterTest.java
This PR slightly improves the file transport to fully utilize FileSystem, which now can be ZipFileSystem as well. The "old" part remains unchanged.
For factory just added `bundle:` prefix, that now may be in form `bundle:fileUri`, where `fileUri` is basically a path of a ZIP file that must exist. The ZIP file is read only.
The point of this PR is that user can now use a "bundle" (see https://central.sonatype.org/publish/publish-portal-upload/) just like we did before with staging repositories. Various tools (njord?) can produce bundles. The ZIP file is "mounted" and artifacts from it becomes reachable to Maven just like from any remote repository.
---
https://issues.apache.org/jira/browse/MRESOLVER-700
=> [MRESOLVER-700] Bundle transport: read support

maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositorySystemSession.java, maven-resolver-api/src/main/java/org/eclipse/aether/repository/AuthenticationDigest.java, maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/ConsoleTransferListener.java, maven-resolver-generator-gnupg/src/main/java/org/eclipse/aether/generator/gnupg/loaders/GpgAgentPasswordLoader.java, maven-resolver-generator-gnupg/src/main/java/org/eclipse/aether/generator/gnupg/loaders/GpgConfLoader.java, maven-resolver-generator-gnupg/src/main/java/org/eclipse/aether/generator/gnupg/loaders/GpgEnvLoader.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTrackingFileManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultUpdatePolicyAnalyzer.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/NodeStack.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/session/DefaultSessionBuilder.java, maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpTransporterTest.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporter.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/GlobalState.java, maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/SharingAuthCache.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterCloser.java, maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/test/java/org/eclipse/aether/transport/jdk/JdkTransporterTest.java, maven-resolver-transport-jetty/src/main/java/org/eclipse/aether/transport/jetty/PutTaskRequestContent.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/ChecksumUtils.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/StringDigestUtil.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/Stack.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/SecretAuthentication.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/UnionVersionRange.java
=> Remove suppressions for checkstyle MagicNumber

maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/Booter.java, maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/SessionBuilderSupplier.java, maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/SessionBuilderSupplier.java
Maven3 supplier lacks `env.` entries from session system properties. Maven4 supplier has no system properties at all set.
Supersedes #539
---
https://issues.apache.org/jira/browse/MRESOLVER-588
Co-authored-by: @HannesWell
=> [MRESOLVER-588] Incomplete system properties in suppliers

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/MMap.java
So that `done()` does not need copy second time.
=> Copy in copy method; otherwise reuse

maven-resolver-transport-http/pom.xml, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/RFC9457/HttpRFC9457Exception.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/RFC9457/RFC9457Parser.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/RFC9457/RFC9457Payload.java, maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/RFC9457/RFC9457Reporter.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpServer.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java, maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/RFC9457/RFC9457ParserTest.java
This PR is a backport of https://github.com/apache/maven-resolver/pull/576 which was an implementation of [RFC9457](https://www.rfc-editor.org/rfc/rfc9457) which adds problem information as a payload. Previously, the reasonPhrase prior to http2 could be used to provide extra information but since http2 this has been dropped.
The backport is required because maven 3.9.x is pinning maven-resolver to 1.9.x
. The previous work was released in 2.0.2.
Slack conversation: https://the-asf.slack.com/archives/C7Q9JB404/p1750487298498529?thread_ts=1750487298.498529&cid=C7Q9JB404
Fixes: https://github.com/apache/maven-resolver/issues/1501
Following this checklist to help us incorporate your
contribution quickly and easily:
Note that commits might be squashed by a maintainer on merge.
This may not …
=> RFC9457 implementation

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapterFactoryImpl.java
The use of file lock seems overkill, as on most normal OSes is just not needed.
Basically this now aligns Resolver 2 with Resolver 1 regarding locking.
=> Make rwlock-local the default

maven-resolver-api/src/main/java/org/eclipse/aether/resolution/VersionRangeRequest.java
The idea is to let caller be able to augment the nature of metadata to resolve version range from.
Resolver already handles this, and is more elegant, than to have caller fiddle with filtering the remote repositories or alike. Also, this way client code (ie. Maven) can expose more fine grained configuration for this.
=> Ability to augment metadata nature for version range request

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictIdSorter.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictMarker.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/transformer/SimpleConflictMarker.java
Improvements to conflict resolver, step one: cleanup and return type safety. This codebase is last that is 100% equal between Resolver 1 and Resolver 2, and was quite "dirty" at least what type safety matters. On may places `Object` was used as type. This PR merely cleans this up, and also revealed one interesting fast: at runtime Maven used `Integer` as conflictID while in tests `String` (for easier debug). This is now aligned, and `String` is used, but at runtime it is still integer counter String representation that is interned (to retain pooled numbers behavior). 
Minor improvements added to `Key` class that now memorizes `hashCode` instead to over and over recalculate it.
After this cleanup we should be able to more easily comprehend and improve conflict resolution.
=> ConflictResolver improvements, preparations

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/GroupTree.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/Node.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/PrefixTree.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSourceTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceTestSupport.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/ruletree/GroupTreeTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/ruletree/PrefixTreeTest.java, maven-resolver-supplier-mvn3/pom.xml, maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, maven-resolver-supplier-mvn4/pom.xml, maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java, src/site/markdown/remote-repository-filtering.md
High level new features and changes:
* (change) filtering is **enabled by default**
* (new) filtering can be suppressed on per-repository basis by appending configuration key with `.repoId=false`.
* (change) both filters enhanced to become really usable.
Is enabled by default (but remains dormant if user does not provides input). It becomes active only when user provides input for it.
Input vastly improved and now supports modifiers as well (Resolver 1.x modus operandi was `=org.apache` ONLY). Hence, upgrading from Resolver 1.x to Resolver 2.x leads to "broadened" filtering but that is fine is was user usually wants (Resolver 1.x had to enumerate all Gs for nested G, ie `org.apache.maven`, `org.apache.maven.plugins` etc... same effect with Resolver 2.x is one liner: `org.apache.maven` (as …
=> Ingest Maveniverse Heimdall

maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/SmartExecutor.java
When Maven/Resolver runs on older than Java 21, the classic thread pools are used, and TCCL must be delegated now that they are reused across session, otherwise lookup issues occurs as Plexus DI will filter components based on it.
As Maven ITs shows, on Java 17 the DAV related ITs fail. They load the DAV Wagon as build extension (from POM). This means that BF used pool is instantiated way before, and pooled threads TCCL are not "aware" of (later) loaded up build extension (IT failes are "no DAV transport available", while the extension _is loaded up_).
With this change locally the ITs pass OK on Java 17, while on Java 21 (where VTs are used) this was never an issue, as we use "one VT per task" and VT is dropped once done (they are not pooled).
Before SmartExecutors, this was not a problem …
=> SmartExecutor: on classic pools TCCL must be delegated

maven-resolver-api/src/main/java/org/eclipse/aether/scope/ScopeManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/scope/ScopeManagerImpl.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionScheme.java
Profiling, the most obvious ones. The scope manager method is HOT, as now we started using scope universe in validation that itself is very hot. These are immutable collections, so no reason to create them in ctor instead per each call.
=> Profiling: most hot spots and possibly wasted thread.

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ClassicConflictResolver.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/PathConflictResolver.java
Basically whoever does `new ConflictResolver(...)` will get "classic" one. Today, doing this should not be needed, only in cases like Maven is.
Fixes #1562
=> Restore ConflictResolver backward compatibility

maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/Maven3ScopeManagerConfiguration.java, maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/SessionBuilderSupplier.java, maven-resolver-supplier-mvn3/src/test/java/org/eclipse/aether/supplier/RepositorySystemSupplierTest.java
As Maven3 is now mature, set in stone, so Resolver 2 can do it. 
Same for Maven4 is not possible (is like chicken-egg situation).
Presence of scope manager allows now new v 2.0 features like "resolving by ResolutionScope", so no need for manual setting up selection of session and filter parameters to achieve wanted effect: just say what scope you want and bam, there it is.
=> Resolver 2 provides scope manager for mvn3

maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ClassicConflictResolver.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/PathConflictResolver.java
There is more needed: the inner helper classes must be reverted to abstract classes (that are really iface-like) but must remain classes to keep compatibility.
=> Restore ConfictResolver backward compatibility

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalPathPrefixComposerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/LocalPathPrefixComposerFactorySupport.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManager.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerFactory.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SparseDirectoryTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/checksum/SummaryFileTrustedChecksumsSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/EnhancedSplitLocalRepositoryManagerTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/RepositoryIdHelperTest.java
Many feature blindly assume (as Maven validates this) that `repository.id` is "path segment"-safe string.
Still, we found some fairly recent POMs (like maven-core 3.6.1!) that contain in their transitive hull POMs that contain FS unsafe repository IDs.
These IDs makes features like split repository, or metadata caching go hay-way.
This PR contains fix for these "bad" repository.id-s (by "fixing" them to be as should: FS safe) covering all places where repository.id is to be used as path segment.
Fixes #1564
=> Repository ID handling improvement

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java, maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java
Problems:
* filter logging is not aligned
* prefix filter logs `null` for path
* transfer logs are irrelevant for most user
Changes:
* align filter logging (both should log all outcomes same way)
* fix log having `null`, file is expected to be `null` at that point
* prevent transport logs, is just noise
=> Improvement: Improve filters logging and lessen noise

maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/FileUtilsTest.java
This change was done due Windows, but later the execution path was split for Windows to use oldie pre-NIO2 code to copy as for some reason that works on Windows.
On other platforms, insist on ATOMIC, still make use able to override it, in case atomic is not a viable option.
=> Go back to atomic

maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestFileUtils.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/AbstractDependencyManager.java
PR #1581 left some typos in, that makes javadoc puke:
```
[ERROR] /home/cstamas/Worx/apache-maven/maven-resolver/maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestFileUtils.java:161: error: unterminated inline tag
[ERROR]      * @deprecated use {@code @TempDir) (JUnit 5) Or {@code TemporaryFolder} (JUnit 4) instead
```
PR #1589 used forbidden chars.
=> Javadoc fixes

maven-resolver-transport-minio/pom.xml, maven-resolver-transport-minio/src/test/java/org/eclipse/aether/transport/minio/MinioTransporterIT.java
Update MinIO and okhttp3 to latest.
=> Update MinIO to 8.6.0

maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/GAVNameMapper.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/BasedirHashingNameMapperTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/BasedirNameMapperTest.java, maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/GAVNameMapperTest.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/PathUtils.java, maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/RepositoryIdHelper.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/PathUtilsTest.java, maven-resolver-util/src/test/java/org/eclipse/aether/util/repository/RepositoryIdHelperTest.java
It caused in certain cases that lock names for different metadata collapsed onto same name, and hence, congestion with possible timeouts on resource happened. In case of metadata, `Metadata#getType` was totally ignored, which turns out was wrong, as today we have more types than the simple `maven-metadata.xml`.
Fix: We already had means to make sure "string is valid for path segment", but it was buried in `RepositoryIdHelper`. Pull it out, and make it reusable, as this is essentially very same use case. Also, this extra work really "punishes" only non maven metadata, and that is okay (right now we have only repository prefix and archetype catalog files in play).
Fixes #1609
=> GH-1609 Bad metadata naming
