- .gitignore
@michael-o eclipse writes these files. We don't want to check them in.
> add checkstyle to .gitignore

- maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporter.java
@michael-o also adds @Override and cleans up the exception handing to the extent possible with changing the public API
> [MRESOLVER-120] use try with resources

- maven-resolver-impl/pom.xml
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRemoteRepositoryManager.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/StubRemoteRepositoryManager.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/StringUtils.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/StringUtilsTest.java
> [MRESOLVER-122] deprecate yet another StringUtils class

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleDigest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactoryTest.java
- src/site/markdown/configuration.md
@dantran Please have a look. This should fully restore service.
> Mresolver 138

- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/locator/Service.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/locator/ServiceLocator.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/locator/package-info.java
Deprecate `ServiceLocator` and `Service` interfaces.
> [MRESOLVER-160] Deprecate service locator

- maven-resolver-util/src/main/java/org/eclipse/aether/util/ConfigUtils.java
Checking type and nullness beforehand can help avoid exceptions (like NullPointerException and ClassCastException) in almost all cases.
Usage of exceptional flow affects performance.
Also catching general Exception is usually considered as bad smell.
> Check if value is really non-null String before attempt to parse it.

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactorySelectorSupport.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/SimpleNamedLockFactorySelector.java
Make SimpleNamedLockFactorySelector logic reusable
> [MRESOLVER-232] Refactor selector

- maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTransporterProvider.java
- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporterFactory.java
Continues of trail of https://github.com/apache/maven-resolver/pull/151
> Fix bad requireNonNull checks, part2

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DataPool.java
The DataPool.descriptors in case of "good" descriptor references it's own key, hence prevents collection of it. Fixing by wrapping the value (descriptor) with `WeakReference`, as proposed user on related JIRA.
---
https://issues.apache.org/jira/browse/MRESOLVER-250
> [MRESOLVER-250] Wrap DataPool descriptors into weak refs

- pom.xml
Update parent POM to 36 and clean up plugin version overrides.
---
https://issues.apache.org/jira/browse/MRESOLVER-254
> [MRESOLVER-254] Update parent POM to 36

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
As DF (original) and BF (added in 1.8) started as copy-paste of each other, they
share a LOT. This PR tries to minimize redundancy, still, not loosing clarity,
so leaving inner Args class for each of them.
---
https://issues.apache.org/jira/browse/MRESOLVER-258
> [MRESOLVER-258] Collapse collectors

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
Seems we missed these while refactoring.
> Remove unused stuff

- pom.xml
Remove version overrides and update bnd plugin
as well.
---
https://issues.apache.org/jira/browse/MRESOLVER-272
> [MRESOLVER-272] Update parent POM to 37, remove plugin version overrides, update bnd

- maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/TestNioLock.java
Using this tool users can validate will file locking work from them from single host. This does NOT validate distributed locking, only the file locking.
> Add a tool to verify file locking on OS/FS/Java combo.

- maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/ChainedLocalRepositoryManager.java
Not for production, but useful in testing environments.
---
https://issues.apache.org/jira/browse/MRESOLVER-297
> [MRESOLVER-297] Chained LRM

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/DependencyResolutionSkipper.java
Changes:
* make skipper closeable
* make parallel descriptor resolver closeable
* the two above should be used within try-with-resource block
* improve encapsulation of resolver
---
https://issues.apache.org/jira/browse/MRESOLVER-317
> [MRESOLVER-317] Improvements for BF collector

- maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/ExecutorUtils.java
- src/site/markdown/configuration.md
Cleanup of scattered/copy pasted code and adding utility class.
---
https://issues.apache.org/jira/browse/MRESOLVER-318
> [MRESOLVER-318] Cleanup redundant code and centralize executor handling

- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersion.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionConstraint.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionRange.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionScheme.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/UnionVersionRange.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/package-info.java
Just a small helper to simplify version parsing peculiarities and compare them to ComparableVersion in cases like MNG-7690 is. The code and output is intentionally copy-paste for simpler output comparison.
No issue created, as this is really not a feature or new API in resolver.
> Small helper similar to maven-artifact ComparableVersion

- maven-resolver-api/src/main/java/org/eclipse/aether/ConfigurationProperties.java
- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java
- maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
- src/site/markdown/configuration.md
Add option for HTTP preemptive auth.
---
https://issues.apache.org/jira/browse/MRESOLVER-315
> [MRESOLVER-315] Preemptive auth

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NameMappers.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/providers/FileStaticNameMapperProvider.java
- maven-resolver-impl/src/site/markdown/synccontextfactory.md.vm
As static does not work with file-lock factory.
---
https://issues.apache.org/jira/browse/MRESOLVER-330
> [MRESOLVER-330] Introduce file-static name mapper

- maven-resolver-api/src/main/java/org/eclipse/aether/resolution/ArtifactResolutionException.java
- maven-resolver-api/src/main/java/org/eclipse/aether/transfer/RepositoryFilteredException.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
When we use remote repository filtering real cause for artifact not found may be hidden.
https://issues.apache.org/jira/browse/MRESOLVER-337
> [MRESOLVER-337] Real cause when artifact not found with repository filtering

- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java
Fix from 7c06f7045cf90012883002f41a5245402b00b849
was partially reverted by 28fec45f15f24bbee8b3584f09425e75ae7104ab
> [MRESOLVER-339] Preemptive auth fix

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultMetadataResolverTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/RecordingRepositoryListener.java
Ensure that METADATA_DOWNLOADING event is sent only once in case the lock "upgrade" happens
> [MRESOLVER-352] - Duplicate METADATA_DOWNLOADING event is being sent

- pom.xml
---
https://issues.apache.org/jira/browse/MRESOLVER-366
> [MRESOLVER-366] Upgrade build plugins

- maven-resolver-named-locks-redisson/pom.xml
- maven-resolver-named-locks-redisson/src/assembly/bundle.xml
- maven-resolver-named-locks-redisson/src/site/markdown/index.md.vm
This PR updates only redisson module: redisson dependency, simplifies installation by providing a "bundle" ZIP and updates site page.
---
https://issues.apache.org/jira/browse/MRESOLVER-367
> [MRESOLVER-367] Update Redisson and related documentation

- pom.xml
---
https://issues.apache.org/jira/browse/MRESOLVER-378
> [MRESOLVER-378] Update parent POM to 40

- maven-resolver-named-locks/src/main/java/org/eclipse/aether/named/support/NamedLockSupport.java
And logged thread diag does not distinguish: "waits for X" or "has X".
---
https://issues.apache.org/jira/browse/MRESOLVER-380
> [MRESOLVER-380] Failed locking attempts are not removed

- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java
- src/site/markdown/configuration.md
> [MRESOLVER-382] allow setting outgoing interface

- maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestFileUtils.java
- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporter.java
- maven-resolver-transport-http/src/test/java/org/eclipse/aether/transport/http/HttpTransporterTest.java
If sent by remote end.
---
https://issues.apache.org/jira/browse/MRESOLVER-393
> [MRESOLVER-393] Transport HTTP should retain last-modified

- maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultArtifactResolver.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalRepositoryProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRemoteRepositoryManager.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryEventDispatcher.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryLayoutProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTransporterProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultUpdateCheckManager.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/legacy/DefaultSyncContextFactory.java
- maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporterFactory.java
All injection points are public and deprecate all def ctors (where ctor injection used).
---
https://issues.apache.org/jira/browse/MRESOLVER-386
> [MRESOLVER-386] Make all injected ctors public, deprecate def ctors

- maven-resolver-named-locks-hazelcast/pom.xml
- maven-resolver-named-locks-redisson/pom.xml
Both are bugfix updates:
* Hazelcast 5.3.1 -> 5.3.2
* Redisson 3.23.2 -> 3.23.4
---
https://issues.apache.org/jira/browse/MRESOLVER-399
> [MRESOLVER-399][MRESOLVER-398] Update Redisson to 3.23.4, Hazelcast 5.3.2

- maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerFactory.java
- maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- maven-resolver-transport-classpath/src/main/java/org/eclipse/aether/transport/classpath/ClasspathTransporterFactory.java
- maven-resolver-transport-file/src/main/java/org/eclipse/aether/transport/file/FileTransporterFactory.java
- maven-resolver-transport-http/src/main/java/org/eclipse/aether/transport/http/HttpTransporterFactory.java
- maven-resolver-transport-wagon/src/main/java/org/eclipse/aether/transport/wagon/WagonTransporterFactory.java
Use NAME constants instead.
---
https://issues.apache.org/jira/browse/MRESOLVER-405
> [MRESOLVER-405] Get rid of component name free string literals

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultLocalRepositoryProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryConnectorProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryEventDispatcher.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositoryLayoutProvider.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultTransporterProvider.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultDeployerTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultInstallerTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultRepositoryEventDispatcherTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSourceTest.java
- maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
Do not inject/convert, inject plain Map instead.
---
https://issues.apache.org/jira/browse/MRESOLVER-419
> [MRESOLVER-419] Preserve component names

- maven-resolver-util/src/main/java/org/eclipse/aether/util/listener/ChainedRepositoryListener.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/listener/ChainedTransferListener.java
- pom.xml
Add ability to extend classes.
---
https://issues.apache.org/jira/browse/MRESOLVER-431
> [MRESOLVER-431] Make chained repository and transfer listeners extensible

- src/site/markdown/upgrading-resolver.md
Closeable session class has been renamed.
---
https://issues.apache.org/jira/browse/MRESOLVER-436
> [MRESOLVER-436] Update page with renames

- maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
Undo changes to code block that worked without any issue on non-Windows OSes.
---
https://issues.apache.org/jira/browse/MRESOLVER-441
> [MRESOLVER-441] Undo FileUtils changes for non-Windows

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/version/DefaultVersionSchemeSelector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/version/GenericVersionSchemeProvider.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/version/VersionSchemeSelector.java
- maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- src/site/markdown/configuration.md
Open the gates to support multiple version schemes (currently per session).
---
https://issues.apache.org/jira/browse/MRESOLVER-446
> [MRESOLVER-446] Introduce version scheme selector

- maven-resolver-test-http/pom.xml
- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpServer.java
- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/RecordingTransportListener.java
- maven-resolver-transport-apache/pom.xml
- maven-resolver-transport-apache/src/test/java/org/eclipse/aether/transport/apache/ApacheTransporterTest.java
- maven-resolver-transport-apache/src/test/java/org/eclipse/aether/transport/apache/HttpServer.java
- maven-resolver-transport-jetty/pom.xml
- pom.xml
Move off dead Jetty 9, and use 10.x in both modules, update to latest minor.
---
https://issues.apache.org/jira/browse/MRESOLVER-448
> [MRESOLVER-448] Align Jetty versions

- src/site/markdown/upgrading-resolver.md
Method is removed in alpha-4
---
https://issues.apache.org/jira/browse/MRESOLVER-454
> [MRESOLVER-454] Remove the gone method from page

- .github/workflows/maven-verify.yml
- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpServer.java
- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpTransporterTest.java
- maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestRepositorySystemSession.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporter.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterCloser.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-21/pom.xml
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-21/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterCloser.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk/pom.xml
- maven-resolver-transport-jdk-parent/pom.xml
- pom.xml
And JDK transport did not close them in case of errors.
---
https://issues.apache.org/jira/browse/MRESOLVER-455
> [MRESOLVER-455] Streaming bodies must be closed

- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/HighestVersionFilter.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/version/LowestVersionFilter.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/versions/HighestVersionFilterTest.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/versions/LowestVersionFilterTest.java
Extend filters to implement top/bottom
---
https://issues.apache.org/jira/browse/MRESOLVER-460
> [MRESOLVER-460] Implement top H/L

- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/ClassicDependencyManager.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/manager/DependencyManagerTest.java
Open up transitive mode for Classic.
---
https://issues.apache.org/jira/browse/MRESOLVER-462
> [MRESOLVER-462] Classic Transitive depMgr

- maven-resolver-supplier/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- pom.xml
---
https://issues.apache.org/jira/browse/MRESOLVER-458
> [MRESOLVER-458] Update to Maven 4.0.0-alpha-10

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapterFactoryImpl.java
Make file lock factory and file-gav mapper the default.
---
https://issues.apache.org/jira/browse/MRESOLVER-264
> [MRESOLVER-264] Make file locking the default

- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersion.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/version/package-info.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/version/GenericVersionTest.java
Fix code and extend UT coverage, and add "spec" to package javadoc.
---
https://issues.apache.org/jira/browse/MRESOLVER-336
> [MRESOLVER-336] Fixes to generic schema

- pom.xml
Use latest Maven 4.
---
https://issues.apache.org/jira/browse/MRESOLVER-469
> [MRESOLVER-469] Update to Maven 4.0.0-alpha-12

- maven-resolver-named-locks-hazelcast/pom.xml
- maven-resolver-named-locks-redisson/pom.xml
- maven-resolver-tools/pom.xml
- maven-resolver-transport-wagon/pom.xml
- pom.xml
Bulk upgrades of dependencies.
Issues:
* https://issues.apache.org/jira/browse/MRESOLVER-473
* https://issues.apache.org/jira/browse/MRESOLVER-474
* https://issues.apache.org/jira/browse/MRESOLVER-475
* https://issues.apache.org/jira/browse/MRESOLVER-476
* https://issues.apache.org/jira/browse/MRESOLVER-477
* https://issues.apache.org/jira/browse/MRESOLVER-478
* https://issues.apache.org/jira/browse/MRESOLVER-479
> Dependency upgrades

- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/NodeListGenerator.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/visitor/NodeListGeneratorTest.java
Rework whole class to use Streams
---
https://issues.apache.org/jira/browse/MRESOLVER-483
> [MRESOLVER-483] Classpath generation bugfix

- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/AbstractDepthFirstNodeListGenerator.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/visitor/AbstractDepthFirstNodeListGeneratorTestSupport.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/visitor/PostorderNodeListGeneratorTest.java
- maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/visitor/PreorderNodeListGeneratorTest.java
As iterator may have more, but no file check is done
---
https://issues.apache.org/jira/browse/MRESOLVER-483
> [1.9.x][MRESOLVER-483] Fix path concatenation logic

- maven-resolver-tools/pom.xml
- pom.xml
Issues:
https://issues.apache.org/jira/browse/MRESOLVER-485
https://issues.apache.org/jira/browse/MRESOLVER-487
https://issues.apache.org/jira/browse/MRESOLVER-488
https://issues.apache.org/jira/browse/MRESOLVER-489
https://issues.apache.org/jira/browse/MRESOLVER-490
> Various updates

- maven-resolver-api/src/main/java/org/eclipse/aether/graph/Dependency.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/SystemScopePredicate.java
No JIRA for this, it is merely about improving existing Javadoc, no new functionality or any other code change happened.
> Improve javadoc

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultChecksumProcessor.java
Addendum 1
---
https://issues.apache.org/jira/browse/MRESOLVER-496
> [MRESOLVER-496] Paths everywhere, addendum 1

- maven-resolver-api/src/main/java/org/eclipse/aether/DefaultRepositorySystemSession.java
- maven-resolver-api/src/main/java/org/eclipse/aether/RepositorySystemSession.java
- maven-resolver-api/src/main/java/org/eclipse/aether/scope/DependencyScope.java
- maven-resolver-api/src/main/java/org/eclipse/aether/scope/ScopeManager.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/scope/ManagedScopeDeriver.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/scope/ManagedScopeSelector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/scope/ScopeManagerImpl.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/session/DefaultCloseableSession.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/manager/AbstractDependencyManager.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/selector/OptionalDependencySelector.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/selector/ScopeDependencySelector.java
Rename method and clean up Javadoc issues.
---
https://issues.apache.org/jira/browse/MRESOLVER-517
> [MRESOLVER-517] Rename scope mgr method and javadoc fixes

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
And introduce one in parent class.
---
https://issues.apache.org/jira/browse/MRESOLVER-519
> [MRESOLVER-519] Drop almost equal/same method copies

- maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/GetDependencyHierarchy.java
- maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/supplier/SupplierRepositorySystemFactory.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/PrioritizedComponent.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/PrioritizedComponents.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Utils.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollector.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultRepositorySystemTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfWithSkipperDependencyCollectorTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/BfWithoutSkipperDependencyCollectorTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/df/DfDependencyCollectorTest.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/artifact/decorator/ArtifactDecorator.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/artifact/decorator/ArtifactDecoratorFactory.java
- maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/visitor/DependencyGraphDumper.java
Added SPI and demo contains example of decorator.
Builds upon [MRESOLVER-519](https://issues.apache.org/jira/browse/MRESOLVER-519)
---
https://issues.apache.org/jira/browse/MRESOLVER-217
> [MRESOLVER-217] Extra sources for Artifact decoration

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultDeployer.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultInstaller.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Utils.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegate.java
Handling of generators, decorators were all duplications.
---
https://issues.apache.org/jira/browse/MRESOLVER-520
> [MRESOLVER-520] Collapse repeated code blocks

- maven-resolver-generator-gnupg/pom.xml
Update BC to 1.78
---
https://issues.apache.org/jira/browse/MRESOLVER-523
> [MRESOLVER-523] Update GPG generator BC to 1.78

- pom.xml
Use parent POM 42.
---
https://issues.apache.org/jira/browse/MRESOLVER-539
> [MRESOLVER-539] Use parent POM 42

- maven-resolver-demos/maven-resolver-demo-snippets/pom.xml
- maven-resolver-named-locks-redisson/pom.xml
- pom.xml
Demos were using implicit sisu index creation that is now disabled in parent, so needs sisu plugin
---
https://issues.apache.org/jira/browse/MRESOLVER-549
https://issues.apache.org/jira/browse/MRESOLVER-550
https://issues.apache.org/jira/browse/MRESOLVER-551
> [MRESOLVER-549] Parent POM 42

- pom.xml
So make possible simultanous release of 1.x and 2.x resolver.
---
https://issues.apache.org/jira/browse/MRESOLVER-552
> [MRESOLVER-552] Redirect site staging

- pom.xml
---
https://issues.apache.org/jira/browse/MRESOLVER-553
> [MRESOLVER-553] Undo site redirection

- maven-resolver-tools/pom.xml
- pom.xml
The 'tools' module is a hack, and must be built last, that may not happen with mvnd. Just added ALL relevant modules to 'tools' as dependencies.
> No source change, just ensure proper module build order

- maven-resolver-generator-gnupg/pom.xml
- maven-resolver-supplier-mvn3/pom.xml
- maven-resolver-test-http/pom.xml
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/pom.xml
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-21/pom.xml
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-8/pom.xml
- maven-resolver-transport-jetty/pom.xml
Follow-up on https://github.com/apache/maven-resolver/pull/512 where the new modules have not been considered.
@gnodet can you please have a look?
> [Build] Unify bnd-maven-plugin and maven-jar-plugin invocations 2 (#509)

- pom.xml
As mentioned in https://github.com/apache/maven-resolver/pull/507#issuecomment-2199623169.
> [MRESOLVER-571] Fix usage of '-noimport' directive on exports

- maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporter.java
As default one is not standard (w00t?)
---
https://issues.apache.org/jira/browse/MRESOLVER-574
> [MRESOLVER-574] Use standard cookie spec

- maven-resolver-demos/maven-resolver-demo-snippets/pom.xml
- maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/util/Booter.java
- maven-resolver-demos/maven-resolver-demo-snippets/src/main/resources/META-INF/sisu/javax.inject.Named
This PR showcases how Maven4+Resolver2 can now run on custom (even in memory like JIMFS is) FileSystem
> Use Google JIMFS for demos

- maven-resolver-transport-minio/pom.xml
- pom.xml
And remove dupe versions from reactor, all use same latest version.
---
https://issues.apache.org/jira/browse/MRESOLVER-630
> [MRESOLVER-630] Bump bouncycastleVersion from 1.78.1 to 1.79

- .github/workflows/maven-verify.yml
Just up to latest Maven version.
> Update Maven in GH workflow

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java
Add the sigstore extension to default values of "omit checksums".
---
https://issues.apache.org/jira/browse/MRESOLVER-680
> [1.9.x] [MRESOLVER-680] Sigstore extension added

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessor.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java
Backport of MRESOLVER-653
---
https://issues.apache.org/jira/browse/MRESOLVER-659
> [MRESOLVER-659] NPE in trusted checksum post processor if artifact resolution failed

- maven-resolver-impl/src/main/java/org/eclipse/aether/impl/RepositorySystemValidator.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystem.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultRepositorySystemValidator.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultRepositorySystemTest.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/validator/Validator.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/validator/ValidatorFactory.java
- maven-resolver-spi/src/main/java/org/eclipse/aether/spi/validator/package-info.java
- maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
- maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
A new extension point that validates values coming into main entry point, the repository system. Provides ability to "hook in" and validate values. Resolver by itself does NOT provide any validator, it is up to integrating app to provide one, if wants.
---
https://issues.apache.org/jira/browse/MRESOLVER-687
> [MRESOLVER-687] Validator SPI

- maven-resolver-api/src/site/site.xml
- maven-resolver-connector-basic/src/site/site.xml
- maven-resolver-demos/maven-resolver-demo-maven-plugin/src/site/site.xml
- maven-resolver-demos/maven-resolver-demo-snippets/src/site/site.xml
- maven-resolver-demos/src/site/site.xml
- maven-resolver-generator-gnupg/src/site/site.xml
- maven-resolver-generator-sigstore/src/site/site.xml
- maven-resolver-impl/src/site/site.xml
- maven-resolver-named-locks-hazelcast/src/site/site.xml
- maven-resolver-named-locks-ipc/src/site/site.xml
- maven-resolver-named-locks-redisson/src/site/site.xml
- maven-resolver-named-locks/src/site/site.xml
- maven-resolver-spi/src/site/site.xml
- maven-resolver-supplier-mvn3/src/site/site.xml
- maven-resolver-supplier-mvn4/src/site/site.xml
- maven-resolver-test-http/src/site/site.xml
- maven-resolver-test-util/src/site/site.xml
- maven-resolver-tools/src/site/site.xml
- maven-resolver-transport-apache/src/site/site.xml
- maven-resolver-transport-classpath/src/site/site.xml
- maven-resolver-transport-jetty/src/site/site.xml
- maven-resolver-transport-minio/src/site/site.xml
- maven-resolver-transport-wagon/src/site/site.xml
- maven-resolver-util/src/site/site.xml
- src/site/site.xml
> Update site descriptors

- Jenkinsfile
PR will be needed https://github.com/apache/maven-jenkins-lib/pull/13
> Deploy snapshot artifacts by Jenkins

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/Maven2RepositoryLayoutFactory.java
For easier transitioning.
Same as MRESOLVER-652, the new property is documented, the old is not, it "just works".
---
https://issues.apache.org/jira/browse/MRESOLVER-701
> [MRESOLVER-701] Support legacy property

- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpServer.java
- maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpTransporterTest.java
- maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporter.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/test/java/org/eclipse/aether/transport/jdk/JdkTransporterTest.java
- maven-resolver-transport-jetty/src/test/java/org/eclipse/aether/transport/jetty/JettyTransporterTest.java
It defaults to HTTP while proxy may be HTTPS
Fixes #745
> Proxy protocol loss

- maven-resolver-demos/maven-resolver-demo-snippets/pom.xml
- maven-resolver-supplier/pom.xml
- maven-resolver-transport-wagon/pom.xml
- pom.xml
- downgrade to plexus-util to 3.6.0
- drop dependencies on plexus-xml
- add enforcer with banned plexus-xml
> Align plexus-util version with Maven

- maven-resolver-transport-minio/src/test/java/org/eclipse/aether/transport/minio/MinioTransporterIT.java
> Stop the container in the shutdown method

- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultFileProcessorTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultMetadataResolverTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultUpdateCheckManagerTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/EnhancedLocalRepositoryManagerTest.java
- maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/SimpleLocalRepositoryManagerTest.java
- maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestFileUtils.java
- maven-resolver-test-util/src/main/java/org/eclipse/aether/internal/test/util/TestLocalRepositoryManager.java
> Deprecate methods that are in JUnit and/or the JDK

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/MetadataResolverSupplier.java
- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java
Also provide a "bridge" to allow generic supplier
injection instead of Guice specific Provider.
> Simplify filters

- maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapterFactoryImpl.java
Reverts 6e673aa186386989e592e82aea0c083b282dbe7a
> Revert default locking change

- maven-resolver-named-locks/pom.xml
- pom.xml
Changes:
* do not manage scope
* slight update: Jetty from 10.0.25 to 10.0.26
* slight update: Junit from 5.13.1 (parent) to 5.13.4
> POM tidy up

- maven-resolver-transport-apache/src/main/java/org/eclipse/aether/transport/apache/ApacheTransporterFactory.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-11/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterFactory.java
- maven-resolver-transport-jdk-parent/maven-resolver-transport-jdk-8/src/main/java/org/eclipse/aether/transport/jdk/JdkTransporterFactory.java
This reverts commit 2ca95ee0b88fe57c216fa7b3edaad555b80de51e.
Fixes #1608
> GH-1608 Revert "Demote JDK transport (#1599)"
